### ISSUE TITLE
2.54B computer Human/orc/elf cannot upgrade main hall

### ISSUE THREAD

**Issue by thecupu** [SMUnlimited/AMAI#10]
hello sir
im already tried from version 1.24B,124E untill 1.31 public realm test warcraft FT OLD

the main problem is
only undead know how to upgrade main hall

Human/orc/elf dont know how to upgrade main hall

i know maybe 2.54B is unsupported know 
but i hope you fix this critical issue at least for community W3 OLD FT

you can also tried with greedisgood and warpten for quickly test result

**Comment by SMUnlimited** [comment]
Not seeing this in 2.6 or 3.0, but this used to be a bug in 2.54 original. Fixed on 19/10/08 for 2.54b. 

Where did you download this version from?

**Comment by thecupu** [comment]
im download 2.54B from this page
https://github.com/SMUnlimited/AMAI/releases

"_Release as it was before the Warcraft 3 reforged era back in 2008 for 1.24b._"
so i try 1.24B-until 1.31 PTR OLD FT
still same problem
 only undead know how to upgrade main hall

im running on win 7 64bit sp1 with single player game with computer insane

here sample 2,54AI 
[sample map ](https://drive.google.com/file/d/1YyJ4BzbPN7QyjKU1qE4WYkhuCT0BiwTC/view)

**Comment by SMUnlimited** [comment]
Maybe i've put the wrong version up, can you try out with the original download links, if those work i'll change it to link to these.

Player Edition
http://www.mediafire.com/download/sq...AMAI2.54PE.rar

Single Edition
http://www.mediafire.com/download/e7...AMAI2.54SE.rar (Will not work with new 1.29 patch)

**Comment by thecupu** [comment]
link not working

**Comment by SMUnlimited** [comment]
Oops http://www.mediafire.com/file/sqr5uzh01l4bgsb/AMAI2.54PE.rar/file

**Comment by thecupu** [comment]
still same , dont know how to upgrade main hall

But , after several test i found something
that bug because i edit _tree hit points life_ for make unlimited trees

and i got message
_this map no longer considered a melee map because
Custom destructible data has been specified_ 

after that human/elf/orc dont know how to upgrade main hall
only undead know how to upgrade main hall

maybe when change to no _more melee map_
there is different system/memory which cause bug
**But, i dont know why thats bug only affected with orc/human/elf**


**i already tested , your AMAI working good if i play original (NO EDIT) map**

**Comment by SMUnlimited** [comment]
Aha, that is because for custom maps it switches to an older patch when you make custom changes which has different upgrade requirements for tier 2. You need to force the custom map to use latest patch dataset.

scenario-> 
map properties->
options->
game data set->
-> Change from Default (based on map melee status) to Latest Patch

**Comment by thecupu** [comment]
> 
> 
> Aha, that is because for custom maps it switches to an older patch when you make custom changes which has different upgrade requirements for tier 2. You need to force the custom map to use latest patch dataset.
> 
> scenario->
> map properties->
> options->
> game data set->
> -> Change from Default (based on map melee status) to Latest Patch

solved with change data set to latest patch
thank you for helping me
