### ISSUE TITLE
function GetLocationInDistanceFromLoc fix

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#106]
https://github.com/SMUnlimited/AMAI/blob/96800f004d3a1ba2d891fa9cbfacaa840401f420/common.eai#L5359

the CreatePathing now is change
set u = CreatePathingUnit(u) will  Create u on home_location
but the function need u Create on loc and move to home_location
so if u Create on home_location , move home_location , u equivalent to not moving

and the function work on towerrush , so if  u Create  home_location , move to loc , will waste a lot of time
maybe need restore required

**Comment by SMUnlimited** [comment]
Yeah this is incomplete but because of the sleep. There shouldn't ever be a sleep in anything called within the Job thread. So this needs reworking to avoid that sleep and to be made correct.

**Comment by jzy-chitong56** [comment]
_There shouldn't ever be a sleep in anything called within the Job thread_

This may be the reason why I have been checking recently and haven't recovered after ignoring the police checkpoint


but  Job thread It already exists

**function TQLoop 
function GetTQLock**


and tq_time[1] - TimerGetElapsed(tq_timer) + 0.05 ， some time is negative

**Comment by jzy-chitong56** [comment]
and here have a bug

```
function CreatePathingUnitFull takes unit u, player p, integer id, real x, real y returns unit
  set u = CreateUnit(ai_player, id, x, y, 270.00)
```

 you use home_location , then u Always at home Create
```
function CreatePathingUnitFull takes unit u, player p, integer id, real x, real y returns unit
    set u = CreateUnit(ai_player, id, GetLocationX(home_location), GetLocationY(home_location), 270.00) 
```

**Comment by jzy-chitong56** [comment]
https://github.com/jzy-chitong56/AMAI/commit/3f5f3948b05baa816d333e998e6b38ba04c67769



_There shouldn't ever be a sleep in anything called within the Job thread._ 
I adjusted the mechanism

you can see now will take up command time, but it's better than taking up JOB time to sleep


just see  TOWER_RUSH_CHECK.eai  cmd_loop  cmd_attack  and  races.eai  StartTowerRush


and
I completely changed GetNearestEnemyDistance , Now take nearest base, not the start loc , if only one human player , all AI will attack the human , but I no set AI cannot attack AI , maybe human player will have .... two dogs strive for a bone , and a third runs away with it
