### ISSUE TITLE
Not working with W3Champions map pool

### ISSUE THREAD

**Issue by Ali229** [SMUnlimited/AMAI#113]
Cannot use this awesome mod for maps that are edited by W3Champion (Melee Maps). Please add this functionality as W3Champion is the only place for quality maps these days.

Steps to reproduce:
1. Download AMAI and installer and configure.
2. Launch AMAI installer and choose "Install on Folder (No Commander)" to install AMAI on W3Champion maps.
3. Play game, AI is vanilla.

Thank you!

**Comment by jzy-chitong56** [comment]
地图包（仅支持1.33+）
链接：https://pan.xunlei.com/s/VNFj0eQVfhhAjpyqb5CSbVtSA1?pwd=7p73#
提取码：7p73

地图池更新到W3C 13赛季（部分更新日期为20221116），已知问题：未连接W3C时新中立建筑图标不生效，新物品图标全部显示绿色，也不知道自定义地图如何在W3C上使用
W3C地图全部转为JASS，W3C功能全部失效
全部地图已设置为最新补丁，应该不会出现不升本的问题

**Comment by SMUnlimited** [comment]
Ultimately maps need to be in JASS mode I think. I unsure what happens when using lua mode maps.

**Comment by jzy-chitong56** [comment]
Lua cannot run, you must convert the map to jass

**Comment by Ali229** [comment]
How to do that?

**Comment by Ali229** [comment]
How to do that?

**Comment by jzy-chitong56** [comment]
https://www.bilibili.com/video/BV11g4y1375Q/

**Comment by paulo101977** [comment]
> How to do that?

>https://www.bilibili.com/video/BV11g4y1375Q/

>@Ali229 but this is Chinese

I watched the video above and it looks like you have to open the map in the Warcraft editor and export it as Jass.
