### ISSUE TITLE
can you examination my pull and Merge Branches?

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#117]
The update is basically completed

can you examination my pull and Merge Branches?  @SMUnlimited 
There are indeed many changes... it seems very troublesome.....

---------------------------------------------------
**KEY change**

> CODE
2.6.2cn code Synchronize to 3.2.2cn ，include bat file ，Without B.J compilation structure , and compatibility not adjusted
2.62cn include 2.6.1cn
3.22cn include 3.1.1cn

> excrete
Improved gaming experience , The cost is an increase over the variable

> Reconstructed TR job
all race can TR 
**of course, the effect is not ideal**

> Reconstructed Harvest job
Fix Official bug - when start point have Multiple gold mines , UD and ELF possible cannot Harvest ,and all race cannot correct expansion，like this
![image](https://github.com/SMUnlimited/AMAI/assets/48715223/643f499d-4521-4e30-9b3c-48f883b8e148)

> Reopen water expansion
ZEPPELIN_FOLLOW JOB can compatible water expansion , and can help AI fix problem of being stuck at home
ZEPPELIN transport peon to expansion can Normal operation

> Reconstructed Rally point job
now can control all races
this can help AI fix problem of being stuck at home

> Item expansion（only  TFT）
New job , the race can use item expansion

> AddBlock Correctly effective and adjust all race AddBlock

>  food upper limit 
now limit  is set according to map , no  longer 100,Perhaps only can rely dynamic training unit code expansion, which may affect the actual effectiveness of the Strategy
![image](https://github.com/SMUnlimited/AMAI/assets/48715223/8b926a3c-5920-499f-a72d-928d7e98a2ef)

> BR
ELF now can use BR , include build and attack （only Non Easy and no TR）
Parameters can be configured : creeprush

> Attack Group take Non self race and custom unit

> Reduce Attack interval ， Attack interval （Combat Sleep count）will be reduced based on the map size and AI difficulty（Only effective on maps of medium size and above），This can shorten the game time for 12 or 24 player map
When the map size is too large, AI will prioritize attacking hunan players
Adapted to 1.29 new map size

> B.J
ZOOM functions optimize （only 2.6.2cn）
MINIMAP Icon （only 3.2.2cn），if map have icon file or folder (like W3C map), writing a new icon file will fail
if debug, all AI will Ally first observer , and sharing control（only initialization take effect）
choose strategy dialog now show strategy translation name （ the English citation name must consistent ，otherwise, the strategy 
button will be missing , AI identify correct strategy cmd）**（Compilation will take a little longer ， Please improve if possible）**
fix Change language cannot back English , because some translations miss variables

> W3C ITEM ICON and Neutral Building ICON
map max file count is 128 
install need use new develop file： w3c minimapicon.js（Windows installer EXE） or InstallTFTtoDir-Icon.pl or  InstallROCtoDir-Icon.pl(only 2.6.2cn) , and need install Commander
2.6.2cn icon file is my custom item blp , no adapter 1.36, no Neutral Building ICON
3.2.2cn icon file is W3C custom dds , adapter 1.36

> W3C Deny unit tip
deny unit now have tip

---------------------------------------------------

**Some demonstrations**
fix start point have Multiple gold mines Harvest fix  - Invalid for official AI
https://www.bilibili.com/video/BV1nP41117LW/

1.30 AI no study skill （only 2.6.2cn）-- valid for official AI
https://www.bilibili.com/video/BV1Lo4y1t7Zd/

---------------------------------------------------

These functions have not been implemented ， regret

**Adapter W3C custom Mercenary** 
Unadapted W3C some map's custom Mercenary
Mercs.txt is 4 unti , W3C map more than 4 custom , and don't want to write dead code

table
```
W3Champions_map(s15)	Mercenary unit 4 code	sellunits
Monopoly v1.5	nmr2	nass,ngnw,nomg,nfsh
Ordeal Ground v1.1	n000	ntkh,nnwl,nwlg,ninc
Rusty Creek v1.3	n000	ndtp,nqbh,nkog,nkol
Vanguard Point v1.4	n000	nmbg,nwlg,nsrh,nsel
```

**AI attack Destructible**
Poor ground attack effect ，and there is also a deviation in the path unit recording position

**AI Take over offline players**
It seems to be a game restriction , not achievable
on game init , if player mapcontrol is user ,  cannot run AI , even if change mapcontrol to computer

**Increase revenue from normal difficulty AI**
Do not want to take advantage of new upgrade in a way

like UPG_WOOD/Rhlh but have add gold

Do not want to use the collected money minus last collected money to increase the difference , This may not be very smooth
global integer variable: **GOLD** and **LUMBER**, init is 0
at peon Harvest functions run the code
set G/L = GetPlayerState(ai_player , PLAYER_STATE_RESOURCE_GOLD/PLAYER_STATE_RESOURCE_LUMBER) - G/L
add G/L num

**Humman Delaying time consumption
human will add game time,When the gold mine has no resources,They can consume ai to die

**Comment by SMUnlimited** [comment]
Thanks, it might take me a while to get it reviewed as its a large change and I don't have alot of time at the moment. 

If you do any future improvements can you create new branches to do that work in as that will make it easier for me.

**Comment by jzy-chitong56** [comment]
Sorry, I didn't consider creating multiple branches



I can record changes to some files on it for reference ,Record my  revision ideas

When you have time, perhaps you can review it faster

**Comment by jzy-chitong56** [comment]
@SMUnlimited 
hope help examination ， maybe need many pull
https://github.com/SMUnlimited/AMAI/pull/122
