### ISSUE TITLE
StartUnitAM why have sleep？

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#119]
StartUnitAM have One line sleep（0.05） code，This can cause Development delay，I don't understand,I think it's maybe use for building, not units

Perhaps at the beginning of the game,This sleep should not be running，For example, before have first hero

**Comment by SMUnlimited** [comment]
Sleeps need to be in a loop to prevent the thread crashing, so the loop in OneBuildLoopAM. Why its specfically within this function no idea.
