### ISSUE TITLE
ARMY_TRACK.eai and DynamicBuildUnit BUG??

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#124]
TrackArmy 
```
  call GroupEnumUnitsInRangeOfLoc(g, army_loc[num], army_radius, null)
  set g = SelectByUnitStandard(g, true)
```

SeedNewArmiesForPlayer 
```
  call GroupEnumUnitsOfPlayer(g, Player(p), null)
  set g = SelectByUnitStandard(g, true)   // Hopefully fix issues of heroes doing other things not making false armies
```

TrackArmy  and SeedNewArmiesForPlayer  will check all player
but UnitStandard only have AI own 
when other player check , the group first unit is null??

--------------------------------------------------------------------------------------------------

DynamicBuildUnit
A neutral mercenary
`call BuildUnit(GetUnitCountDone(old_id[chosen_counter_unit] + 1), chosen_counter_unit, prio)`
GetUnitCountDone(old_id[chosen_counter_unit] + 1)

should
GetUnitCountDone(old_id[chosen_counter_unit]) + 1

**Comment by SMUnlimited** [comment]
The trackarmy is not an issue. The selectbystandard filter will just do nothing for the other players.
