### ISSUE TITLE
2.54/2.6.2 undeads stucks on some maps (resolved)

### ISSUE THREAD

**Issue by Mitradis** [SMUnlimited/AMAI#126]
2.54/2.6.2 undeads stucks on some maps (1.26a)

1 Select, for example, map (6)StranglethornVale.w3x
2 Set 4 Undeads in your team + 1 any enemy
3 Start game and look how some random undeads stucks

**Comment by jzy-chitong56** [comment]
I suspect it was caused by too many gold mines at the player birth loc

the bug will let UD and ELF cannot harvest mine

if you can try this , I fix the bug
https://github.com/jzy-chitong56/AMAI/tree/2.6.x

**Comment by Mitradis** [comment]
no. this version have same behavior:
![WC3ScrnShot_072323_095920_01](https://github.com/SMUnlimited/AMAI/assets/21084600/afe0a1d2-b628-4ef2-9fd5-ec5eea6ab46b)
![WC3ScrnShot_072323_095927_02](https://github.com/SMUnlimited/AMAI/assets/21084600/7353be42-5bd0-44f2-bd3b-104e122b2490)

**Comment by jzy-chitong56** [comment]
yes, 1.27 have this bug too , but 1.36 no this bug
 i will check code
![WC3ScrnShot_072323_172130_000](https://github.com/SMUnlimited/AMAI/assets/48715223/d6c3ac42-325b-436e-a8f8-ee63e0eba192)

**Comment by Mitradis** [comment]
ty for keeping suporting old versions.

**Comment by Mitradis** [comment]
@jzy-chitong56 for some reason UD can leave mine even if his have a lot gold
![WC3ScrnShot_072323_202135_01](https://github.com/SMUnlimited/AMAI/assets/21084600/22bfc78b-aa3b-4fbc-be3e-02400edc2149)

**Comment by jzy-chitong56** [comment]
yes ，&nbsp;There is indeed a problem ， but shouldn't have happened
I suspect there aren't enough peon ， here cannot see AI how many peon ,&nbsp;I can't say it's not a bug, but I really want to say it's not a code issue




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SMUnlimited/AMAI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月24日(星期一) 凌晨1:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SMUnlimited/AMAI] 2.54/2.6.2 undeads stucks on some maps (resolved) (Issue #126)





 
@jzy-chitong56 for some reason UD can leave mine even if his have a lot gold

**Comment by Mitradis** [comment]
this screenshots from one game. One mine empty and first mine have only 4 acolyte
![WC3ScrnShot_072423_000940_01](https://github.com/SMUnlimited/AMAI/assets/21084600/63c665ce-b483-49db-a8a1-4dc2fd056234)
![WC3ScrnShot_072423_000958_02](https://github.com/SMUnlimited/AMAI/assets/21084600/c257e898-867d-4c59-b3e6-025f275aa77e)

**Comment by jzy-chitong56** [comment]
Now try downloading again

**Comment by Mitradis** [comment]
This map bug (game bug), not AMAI. I tested on 2.54b on 1.26a patch and found this:
if you add in main:
function main takes nothing returns nothing
call InitDigits()
call DisplayTimedTextToPlayer(GetLocalPlayer(),0,0,15,Int2Str(GetMinesOwned()))

you can see how on bugged maps code show how some random player have 2 owned mines on start game.
**You can put a point on this. Unable to fix game engine issue caused by unknown map data.**

**Comment by jzy-chitong56** [comment]
YES , this GetMinesOwned BUG , but AMAI should fix , This question has caused UD and ELF cannot harvest , but human and orc have bug too , especially in other gold mines very close to birth point , when they expansion , maybe will build more hall , and they not need to waste so much  , form elf , if distance slightly distant,  they cannot use tree ravel mine , they will build new tree , waste so much

--------------------------------------------------------------------------------------------------------

and I did hear someone say that this is not as good as 2.54 , My version is based on 3.2.2 ， all code synchronization ,  when you said broken , I really don't understand , In theory, 3 is better than 2

**Comment by Mitradis** [comment]
lol this can be fixed by set mine faction to "neutral-hostile" and game engine not add

**Comment by Mitradis** [comment]
@jzy-chitong56  i have some idea how to fix this. Possible at start game remove all mines and spawn their back? can you write this function?

**Comment by Lolasik011** [comment]
@jzy-chitong56 Can you please post Amai installation instructions in English? I unfortunately do not understand Chinese. 
Also if you can please update version 2.6.2 so that it can be installed via Installer. 
Thank you for your work !

**Comment by Mitradis** [comment]
@Lolasik011  same as original. install Strawberry Perl - MakeOptTFT.bat - AMAI.exe select maps and install

only 6 maps have problem with mines and this problem in maps not in amai:
(10)DustwallowKeys
(8)Friends
(6)UpperKingdom
(6)StranglethornVale
(6)Moonglade
(6)EnakrosWay
i am just edit this maps and move expand away from each other.

**Comment by Mitradis** [comment]
i reopen this if someone will face the same.

**Comment by jzy-chitong56** [comment]
@Lolasik011   I  understand English

@Mitradis  no need , now AMAI can fix the problem

**Comment by Mitradis** [comment]
For 2.54b, he is better.

**Comment by Lolasik011** [comment]
@jzy-chitong56 The latest builds of 2.6.2 that you release are not installed via the Amai.exe file.
Yes and I asked to translate you Chinese manual into English at least if possible https://docs.qq.com/doc/DZkpJZkRqb3dPRmh0

**Comment by Lolasik011** [comment]
@Mitradis Please explain to me how to install Amai 2.6.2 (I mean not the version that is in the releases). I would like to play Amai 2.6.2 build which is updated almost every day. Amai 2.6.2 which is in Release is already outdated.

**Comment by Slayer95** [comment]
@Lolasik011 add me on Discord a ``icesandslash``. I'll explain it to you.

**Comment by Mitradis** [comment]
Новое не значит лучше. Есть в двух словах. Любой програмный продукт, после завершения активной фазы разработки, скатывается в говно если его пытаются изменять люди не разрабатывающие его.

**Comment by Slayer95** [comment]
I tested your branch this morning, @jzy-chitong56 , and this issue seems to be fixed.

I suggest locking this thread, since most comments here are unguided rants left and right.
