### ISSUE TITLE
ROC scripts true can run on 1.30 and 1.31

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#131]
1.30 and 1.31 can run ROC
Test Passed

`This version is intended to be played in the original ROC (Reigns of Chaos) version of the game. This version is currently not supported in 1.30+.`

**Comment by SMUnlimited** [comment]
Its not supported only because blizzard disabled ROC in 1.31 and everyone was upgraded to TFT regardless.

**Comment by jzy-chitong56** [comment]
no，1.31 can still enter![image](https://github.com/SMUnlimited/AMAI/assets/48715223/b0514a64-7625-4f46-86ca-fa818aeeb2f1)
