### ISSUE TITLE
Amai v 2.6.2

### ISSUE THREAD

**Issue by Lolasik011** [SMUnlimited/AMAI#137]
Hello
I often play the build which is updated by @jzy-chitong56  almost every day . But it happens that the build either does not work or has critical errors. And I would like to know what is the difference between these branches? 
Where is the stable new version 2.6.2 and where is the one that is frequently updated and which is constantly modified?
Thank you for working on AMAI !

What is the difference between these branches ?
![261434161-fc38ebdc-ef24-4fa2-b7f7-b933c0b13d44](https://github.com/SMUnlimited/AMAI/assets/41998977/b11f7bf3-b8ac-4357-bc6d-689f8d8a02e5)

**Comment by jzy-chitong56** [comment]
Attempt to fix the sudden decrease in FPS, I have been working on this for a long time and it is almost complete, but I have been unable to fully solve it. I have been optimizing the code for over a month and there are no new features available

if you need a stable version,You can try downloading during the day from Monday to Friday in China. If there are compilation errors, can you show me screenshots

**Comment by Lolasik011** [comment]
> Attempt to fix the sudden decrease in FPS, I have been working on this for a long time and it is almost complete, but I have been unable to fully solve it. I have been optimizing the code for over a month and there are no new features available
> 
> if you need a stable version,You can try downloading during the day from Monday to Friday in China. If there are compilation errors, can you show me screenshots
> 
> Don't use slow synchronization branch. It is incomplete. Many of my contents are not completely synchronized to the author

I'll use the 2.6.x branch then :)

If anything, I'll let you know if I find any bugs.

**Comment by jzy-chitong56** [comment]
But you said it couldn't run? Did you successfully run it?

**Comment by Lolasik011** [comment]
> But you said it couldn't run? Did you successfully run it?

Yes I have everything working but the AI behaves strangely he is very bad at attacking and bad at destroying creeps. Also often just does not do anything.  2.6.2 Aug 17, 2023
The AI just stands on the base and hoards resources :D
![image](https://github.com/SMUnlimited/AMAI/assets/41998977/07b315ab-cf72-4b52-a78a-f3ca6f00e747)


Version 2.6.2 Aug 16, 2023 works better and more stable there such problems are not observed there

**Comment by Lolasik011** [comment]
@jzy-chitong56 Do you have your own channel where you test AMAI ? 
Or at least a site where I can see what I need to test and what changes have been made to AMAI.

**Comment by jzy-chitong56** [comment]
I fixed the issue of not attacking last night. I can only say that if his attack and construction are normal, there is nothing to test. 
But some people do say that some races may train their first hero later, or that the hero's movement path may be abnormal, and so on


I only focus on FPS for testing,I think this is the primary issue to solve. Optimizing the code process will indeed generate many new problems. If you have a version that you feel is okay, please do not update it too quickly

**Comment by Lolasik011** [comment]
> I fixed the issue of not attacking last night. I can only say that if his attack and construction are normal, there is nothing to test. But some people do say that some races may train their first hero later, or that the hero's movement path may be abnormal, and so on
> 
> I only focus on FPS for testing,I think this is the primary issue to solve. Optimizing the code process will indeed generate many new problems. If you have a version that you feel is okay, please do not update it too quickly

I like to use the newest versions because there are fixes and lots of new changes :)

If I find any problems or bugs I will let you know.

**Comment by Lolasik011** [comment]
These are the bugs I found !

BUGS AI
By the way, I notice that the AI very rarely pick up artifacts that fall from creeps.

Also, the AI often stretches its army too much and thus attacks with some units rather than the full army .

AI uses Town Portal Scroll rather late and thus AI heroes are often death.

**Comment by Lolasik011** [comment]
@jzy-chitong56 Bug 
AI Human uses workers to clear points from creeps BUT the time when workers were militia is gone and AI just uses regular workers and thus hinders the progress of development of its base and resource collection 
![image](https://github.com/SMUnlimited/AMAI/assets/41998977/fdee31f9-fbdf-43d1-a74f-bb622933a317)

**Comment by jzy-chitong56** [comment]
Still dealing with the airship issue
Militia can take a look on the way

Let's forget about hero death, beyond our my ability range

**Comment by Lolasik011** [comment]
@jzy-chitong56 New bugs
Night Elf destroyed an additional base of Undead and Undead at that time does not react to this and goes to attack the main base of the Night Elves.
![WC3ScrnShot_082423_154618_01](https://github.com/SMUnlimited/AMAI/assets/41998977/91f86622-8039-4259-bbfd-b54b5b0b36f6)

**Comment by Lolasik011** [comment]
New Bug @jzy-chitong56 
AI writes to the chat room after its death :D
![lol](https://github.com/SMUnlimited/AMAI/assets/41998977/b67a9bac-7288-4dcd-bccb-56dbf8d93212)

**Comment by jzy-chitong56** [comment]
I am aware of this issue and have been tracking it for half a month. I am still investigating it, which is also the reason why it has not been officially released

**Comment by Lolasik011** [comment]
@jzy-chitong56  AI forgot units :) Although the AI is fighting now and all units are needed.
![image](https://github.com/SMUnlimited/AMAI/assets/41998977/ec459b8a-fe07-4973-b7e5-864ecb4da283)
![image](https://github.com/SMUnlimited/AMAI/assets/41998977/d9e8d4e6-85d8-466d-b1cf-839861b502f6)
![image](https://github.com/SMUnlimited/AMAI/assets/41998977/9caaf9ef-0158-406b-8c64-4cfeadc40776)

**Comment by jzy-chitong56** [comment]
I broke the logic ，It should be fixed now

_The AI has lost the battle and the units are still standing still_

some time , AI cannot use portal , should get some bug let human player will

and you is Russian？
can you check  Languages error , I noticed other Languages have some garbled code
or let you code Programmer friend check

if you can , see here , one by one check
**Languages\Russian**

need Correct editor and encoding opening , like vscode

**Comment by Lolasik011** [comment]
> I broke the logic ，It should be fixed now
> 
> _The AI has lost the battle and the units are still standing still_
> 
> some time , AI cannot use portal , should get some bug let human player will
> 
> and you is Russian？ can you check your Languages error , I noticed other Languages have some garbled code or Translation Error
> 
> if you can , see here , one by one check **Languages\Russian** or https://github.com/jzy-chitong56/AMAI/tree/master/Languages/Russian
> 
> need Correct editor and encoding opening , like vscode

I've already fixed some of the russian translation 
Translated lines that were not translated, corrected missing and extra symbols.
I am from Ukraine :)

**Comment by jzy-chitong56** [comment]
sorry , Then I hope you will cease the war as soon as possible
Invaders won't win
You can directly submit the branch to SMUnlimited 
I will synchronize

**Comment by jzy-chitong56** [comment]
It doesn't matter anymore. I'll have time to deal with it later

**Comment by Lolasik011** [comment]
@jzy-chitong56 I checked my translation fixes and tweaks and they work fine :)

BUT after your updates some of the translation lines look like unreadable symbols . I have also already fixed this !

I will be to fix the translation permanently after you release your updates

**Comment by jzy-chitong56** [comment]
Did you recompile and view it in the game?

**Comment by Lolasik011** [comment]
> Did you recompile and view it in the game?

Yes everything looks normal BUT after each of your updates some russian words turn into strange symbols.

**Comment by jzy-chitong56** [comment]
![image](https://github.com/SMUnlimited/AMAI/assets/48715223/78ff219d-92b2-4a6a-9b2c-d1db337cb850)

![image](https://github.com/SMUnlimited/AMAI/assets/48715223/10a20d3b-629b-4833-bb22-287eecdc3d4d)

![image](https://github.com/SMUnlimited/AMAI/assets/48715223/274c866f-64c9-4bf5-8496-f220f7c05cae)

![image](https://github.com/SMUnlimited/AMAI/assets/48715223/887af8d8-db62-417b-a7ef-b997637d36fd)

Can you tell what's wrong

**Comment by Lolasik011** [comment]
> Can you tell what's wrong

Everything is fine BUT because you are using Chinese translation of Warcraft 3 game you have a big distance between letters :)

**Comment by jzy-chitong56** [comment]
but you said  **some russian words turn into strange symbols.**
now is have ?

**Comment by Lolasik011** [comment]
@jzy-chitong56 It's fine now :)
![image](https://github.com/SMUnlimited/AMAI/assets/41998977/aef720ad-89b2-48ab-b42d-86790ab87170)
![image](https://github.com/SMUnlimited/AMAI/assets/41998977/539ae46d-53b4-45bc-a21a-185ec840bd38)
![image](https://github.com/SMUnlimited/AMAI/assets/41998977/8c18ae6f-b367-4cb9-a02e-335929b9bcfd)
![image](https://github.com/SMUnlimited/AMAI/assets/41998977/161b1cd4-2003-4c18-8255-8bdf112f3484)
![image](https://github.com/SMUnlimited/AMAI/assets/41998977/c75f3998-25cd-499d-a8bc-a00480f1733c)

**Comment by SMUnlimited** [comment]
I'm closing this as your issues are resolved and 2.6.x is now available from master.
