### ISSUE TITLE
Requesting licensing for project

### ISSUE THREAD

**Issue by Slayer95** [SMUnlimited/AMAI#138]
Hello, @SMUnlimited . I am working on a pet project with the goal of backporting the latest Reforged mechanics and ladder maps to legacy (1.26) Warcraft (excluding graphics). In order to accordingly update the AI behavior to match the newer tech-tree and game mechanics, and for proper gameplay, it's my humble wish to incorporate a forked version of your excellent AMAI project in the backported maps.

Therefore, as per point 4) of the AMAI License, I request permission for doing so.

Thanks for your attention.

- Slayer95 aka IceSandslash

**Comment by SMUnlimited** [comment]
Hi approved, 

2.6.2 is the latest AMAI released version that works for that legacy war3 version, but jzy-chitong56 has been doing some great work also on this branch which would be good to get included.
