### ISSUE TITLE
If scripts cannot be found in required directory installer should throw an error

### ISSUE THREAD

**Issue by SMUnlimited** [SMUnlimited/AMAI#143]
Instead it silently works even though script files are not present, e.g

#### Installing into file: E:\Files\Documents\Warcraft III\Maps\AMAI\(2)bootybay.w3m ####
Resize map hashtable size E:\Files\Documents\Warcraft III\Maps\AMAI\(2)bootybay.w3m
Add ai scripts E:\Files\Documents\Warcraft III\Maps\AMAI\(2)bootybay.w3m
Add commander script E:\Files\Documents\Warcraft III\Maps\AMAI\(2)bootybay.w3m
Optimize map MPQ E:\Files\Documents\Warcraft III\Maps\AMAI\(2)bootybay.w3m

**Comment by paulo101977** [comment]
@SMUnlimited I can help with this problem. What would be the idea if the script is not found? An alert in the installer? And maybe the interruption of the entire installation process?

**Comment by SMUnlimited** [comment]
Hey @paulo101977 
Yeah just an error in the message pane preventing the install from starting when core ai scripts cannot be found, along the lines of

`"AI script 'common.ai' not found in 'resources/scripts', please ensure you have included the scripts folder from AMAI to this location"`

**Comment by paulo101977** [comment]
> Hey @paulo101977 Yeah just an error in the message pane preventing the install from starting when core ai scripts cannot be found, along the lines of
> 
> `"AI script 'common.ai' not found in 'resources/scripts', please ensure you have included the scripts folder from AMAI to this location"`

Right! I'll take a little time and check it out.
