### ISSUE TITLE
GetHeroToBuyItem still  have bug

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#160]
```

function GetHeroToBuyItem takes unit shop, real limit, boolean is_healing_included returns unit
  local integer i = 1
  loop
    exitwhen i > 3
    if hero_built[i] and UnitAlive(hero_unit[i]) then
     if GetSlotsFreeOnUnit(hero_unit[i]) > 0 and DistanceBetweenUnits(hero_unit[i], shop) < limit and not IsUnitInGroup(hero_unit[i], unit_buying_tavern) and not IsUnitInGroup(hero_unit[i], unit_buying_merc) and not IsUnitInGroup(hero_unit[i], unit_harassing) then
       if IsUnitInGroup(hero_unit[i], unit_healing) and is_healing_included then
       else
          return hero_unit[i]
       endif
     endif
    endif
    set i = i + 1
  endloop
  return null
endfunction

```

if IsUnitInGroup(hero_unit[i], unit_healing) and is_healing_included then 
here cannot work 

input is 
      set shop_sent = GetHeroToBuyItem(shop_unit, shop_distance_limit,false)
      set shop_sent = GetHeroToBuyItem(shop_unit, shop_distance_limit,true)

so should 
if IsUnitInGroup(hero_unit[i], unit_healing) == is_healing_included then

fix on https://github.com/jzy-chitong56/AMAI/commit/9ae7b41329361c3a48ef59ef5483a94527b667af

**Comment by SMUnlimited** [comment]
Looks correct to me apart from the confusion, if a racial item and in the unit_healing group still allow the hero to buy the item

if buy_type[id] == BT_RACIAL_ITEM then
		set shop_sent = GetHeroToBuyItem(shop_unit, shop_distance_limit,false)

Otherwise its set to true and hurt hero won't be sent to merchant shops.

**Comment by jzy-chitong56** [comment]
if IsUnitInGroup(hero_unit[i], unit_healing) and is_healing_included then

you sent this
set shop_sent = GetHeroToBuyItem(shop_unit, shop_distance_limit,false)
or 
set shop_sent = GetHeroToBuyItem(shop_unit, shop_distance_limit,true)

but here is
if IsUnitInGroup(hero_unit[i], unit_healing) and false then
or 
if IsUnitInGroup(hero_unit[i], unit_healing) and true then

this can work??

**Comment by SMUnlimited** [comment]
Yes you don't need to do a comparison == for boolean variables
