### ISSUE TITLE
(Reforged) Handle Cloak of Shadows item

### ISSUE THREAD

**Issue by Slayer95** [SMUnlimited/AMAI#167]
In Reforged versions, Cloak of Shadows no longer uses Night Elf Shadowmeld ability (Ashm), but introduces a new ability AIhm, which should work both day and night.

**Comment by jzy-chitong56** [comment]
https://github.com/jzy-chitong56/AMAI/commit/0f04bf771e1fd4f6348644e2e670ee88559758ed

**Comment by Slayer95** [comment]
Thanks, @jzy-chitong56 !

**Comment by jzy-chitong56** [comment]
send home and moonwell job have AIhm control , too
but here just control unit , no control hero , so I donot add AIhm , To maintain its original functionality
