### ISSUE TITLE
AMAI vs AI uses an outdated blizzard.j

### ISSUE THREAD

**Issue by SMUnlimited** [SMUnlimited/AMAI#17]
The AMAI vs AI logic doesn't use the standard blizzard.j file.

Find a way to allow this to be upgraded easily when we update the blizzard.j files for the standard AMAI.

**Comment by Pixyy** [comment]
I find the latest blizzard.j file in Warcraft III\_retail_\scripts\backup\ . Not sure if this is what you want.
[blizzardj.zip](https://github.com/SMUnlimited/AMAI/files/6921042/blizzardj.zip)

This file is smaller than the Blizzard.j file under the AMAI_3.01\Scripts folder
