### ISSUE TITLE
CreatePathingUnitFull cannot Create ai_player PathingUnit on anywhere

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#175]
GetLocationInDistanceFromLoc  now use CreatePathingUnitFull

but TR use GetLocationInDistanceFromLoc  

if CreatePathingUnitFull Create unit no take p , just use ai_player  , then TR will expose enemy loc

and send player p is meaningless

`function CreatePathingUnitFull takes unit u, player p, integer id, real x, real y returns unit`

or
GetLumberLocationAtBase should use 
    set u = CreateUnit(Player(PLAYERPASSIVE), groundid, GetLocationX(home_location), GetLocationY(home_location), 270.0)

-----------------------------------------------------------------------------------------------------------------
But anyway , cannot Create ai_player  unit , the maybe will expose enemy loc

**Comment by SMUnlimited** [comment]
You can't use the neutral passive player. Using passive players results in the invisible units not moving continually. They stop and start. Its hardcoded behavior in the neutral players unfortunately.
