### ISSUE TITLE
BuildMovePeonZeppelin should cannot work on Water Expansion

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#180]
when build_zeppelin not null , the Water Expansion judgment will not continue ， so it cannot call BuildMovePeonZeppelin

the zeppelin expansion key is BuildMovePeonZeppelin control zeppelin and set peon , if not call the function , just cannot expansion
Anyway, just need determine if the zeppelin exists

maybe is 
```
    if (IsWaterExpansion(current_expansion) or IsUnitInGroup(current_expansion, far_expansion) and neutral_available[NEUTRAL_OBSERVATORY] then
      if build_zeppelin == null or not UnitAlive(build_zeppelin) then
        if not UnitAlive(build_zeppelin) then
          call GroupRemoveUnit(unit_zepplin_move, build_zeppelin)
        endif
        set build_zeppelin = GetUnusedZeppelinNearUnit(build_zeppelin, expansion_peon)
        if build_zeppelin == null then
          call Trace("No Zeppelin found for transporting peon")
        else
          call GroupAddUnit(unit_zepplin_move, build_zeppelin)
        endif
      endif
      call Trace("AMAIStartexpa: Is a water or far expansion so using zeppelin")
      if  build_zeppelin == null or not BuildMovePeonZeppelin(peon, current_expansion) then
        call Trace("AMAIStartexpa: zeppelin cannot expansion or exping")
        set peon = null
        return BUILT_SOME
      endif
      set peon = expansion_peon
    endif
```

https://github.com/SMUnlimited/AMAI/blob/36eb0ea87d969b94c7c312c31ba6f1cd9dc4d50c/common.eai#L10143C2-L10143C3

**Comment by SMUnlimited** [comment]
The far_expansion will be blocked again which breaks the game if they haven't bought a zepplin and don't have a way to get one for some reason. Water expansion should wait for zepplin as no other way to get to the mine.

My logic is wrong though as should be an "or" on BuildMovePeonZeppelin not an and.
