### ISSUE TITLE
Will the follow-up author try to support the AI ​​of survival games, such as Jurassic Park?

### ISSUE THREAD

**Issue by xiongsircool** [SMUnlimited/AMAI#182]
Will the follow-up author try to support the AI ​​of survival games, such as Jurassic Park?

**Comment by SMUnlimited** [comment]
Various games we all may in the future mod, or we secretly currently mod :) but this is war3.

**Comment by xiongsircool** [comment]
> Various games we all may in the future mod, or we secretly currently mod :) but this is war3.
Thank you for your hard work, and I wish you all the best in your endeavors. There is no problem.
