### ISSUE TITLE
In Spectator mode, the camera view is very close to the ground .

### ISSUE THREAD

**Issue by Lolasik011** [SMUnlimited/AMAI#183]
![image](https://github.com/SMUnlimited/AMAI/assets/41998977/3ed14b7f-5428-4027-8a9c-9d71b7edef27)

Please fix it. Earlier when I watched AI battle by default the camera at the beginning of the game had a much higher view. Now it's impossible to watch battles normally.

**Comment by jzy-chitong56** [comment]
https://github.com/SMUnlimited/AMAI/pull/181

Look at the w3c keyword line. 
My previous code has changed the default height for Observer and can be added back if needed

**Comment by SMUnlimited** [comment]
Master is based on latest version of warcraft where there is official support to change your zoom level in game.

This is only of use in the 2.6.x branch where such support does not exist so won't include in master.
