### ISSUE TITLE
No Resources for shredder

### ISSUE THREAD

**Issue by SMUnlimited** [SMUnlimited/AMAI#186]
AMAI especially undead can get stuck if they don't have enough wood for the shredder, but then don't have any ghouls either to get that wood. 

Had more than enough gold to do so but was stuck.

**Comment by jzy-chitong56** [comment]
I just adjusted here
As I mentioned before, when the base upgrade completed, but high-level barracks not built done, AI should continue to build low-level units. 
So I checked all strategy build sequences，and found that some of them intentionally built Zeppelin ,So I incorporated the construction of the Zeppelin into the Global build

When I wanted to handle the logging machine in the same way, I found that building logging machine had a dedicated functional control in C.eai
Perhaps just by increasing the judgment of wood, you can preliminarily avoid this problem

**Comment by jzy-chitong56** [comment]
The key is still the build sequence,Previously, I fixed the issue where elf build may stop at the beginning of the game, but in reality, this issue can exist at any time，Either A or B

The best way is possible to bottom out and skip stuck areas（Remove from build_length）, but it will not affect the unit construction required by the strategy (whether it is quantity or type)
