### ISSUE TITLE
Camera zoom problems on older versions of Warcraft 3

### ISSUE THREAD

**Issue by Lolasik011** [SMUnlimited/AMAI#190]
@jzy-chitong56 @SMUnlimited 
The old version of Warcraft 3 doesn't have a camera remotions option. Can you please make it like it used to be so that at the start of the game (in observer or referee mode) the camera is remote. At the moment it is impossible to normally watch matches in the mode of referee and observer as it is impossible to prescribe the zoom command.

![image](https://github.com/SMUnlimited/AMAI/assets/41998977/6245141c-5caf-430d-bff7-2e9aeb0c63d2)

**Comment by jzy-chitong56** [comment]
fix

**Comment by Lolasik011** [comment]
> fix

Can you make the camera a little higher still ? :)
Thank you

**Comment by jzy-chitong56** [comment]
The initial value cannot satisfy everyone, perhaps we need to try other methods
