### ISSUE TITLE
Version support for older natives

### ISSUE THREAD

**Issue by SMUnlimited** [SMUnlimited/AMAI#193]
So the version folders themselves can specify the natives and commons and blizzard.j available rather than AMAI have a single copy.

**Comment by jzy-chitong56** [comment]
This is very awkward. 
The refuge, save, and transfer Scepter functions of my branch use the skill cooldown API. 
This native interface cannot be simulated in lower versions without a third-party map editor's custom library, so need record use time and Hard coding cooldown time,

This requires declaring timing variables for each item first, and in the new version, these extra variables will become redundant

I'm sorry,I have been checking 23 AI player for issues that may cause game crashes, After checking for a while,but cannot find the cause, so I suspect everything (including declaring too many global variables)
