### ISSUE TITLE
Vanilla VS AMAI Ice Crown, AMAI lost

### ISSUE THREAD

**Issue by SMUnlimited** [SMUnlimited/AMAI#195]
6 v 6 Normal difficulity
Various issues
- Undead failed to mine from expansion, but did build the mine on it.
- Slow to expand in general so vanilla AI just overran AMAI as it had multiple mine income much earlier.
- Issue where all AMAI were trying to defend a single spot that did not have any towns so suicided all units there continuously (could be related to town tracking issues)

**Comment by jzy-chitong56** [comment]
The main initiator of expansion now is **ExpansionBuilder**. Your conditions here are set too harshly. Although I have added active expansion, the code conditions in the last five or six lines are indeed very strict

In addition, the expansion of undead structures does not require time judgment, as other races have already determined time，I have never understood

Finally,Will the combination of strategic units be unable to compete with mixed forces?

**Comment by SMUnlimited** [comment]
Next idea i'm going to use upkeep level and systems to push AMAI to consider expansion to 1 or 2 mines so its not just a random time limit but based on actual need.

**Comment by jzy-chitong56** [comment]
Expansion is justExpansion is just one issue, another issue is saving units. If a unit is saved and does not receive healing ，Relying solely on automatic recovery capability, it is occupying population. For AI, they usually exclude units with less than 50% health from the attack group. Blizzard's API seems to follow this logic, but for AMAI, it is usually less than 10%, which leads to longer recovery time,AI basically doesn't have low health units. Without units, he trains a new one that is full of health, resulting in a situation where the population is comparable but there are not many units that can actually be put into combat. This is even more serious on maps without Spring of Water
