### ISSUE TITLE
Allow multiple harass groups at once

### ISSUE THREAD

**Issue by SMUnlimited** [SMUnlimited/AMAI#199]
From [jzy-chitong56](https://github.com/jzy-chitong56)

> on function StartHarass add duplicate check mechanism
> 
> **not IsUnitInGroup(u, unit_harassing)**
> 
> then you can get different **Harass groups**
> 
> and you can use key identifying this groups , and then control it separately
> 
> Now no matter how many unit groups are added, they all share the same set of data , Because **local integer key = GetHandleId(harasser)** always gets the same number every time so all group use same data , one group stop , all group stop **local real strength_limit = LoadReal(additional_info, key, STRENGTH_LIMIT) local boolean state_attacking = LoadBoolean(additional_info, key, STATE_ATTACKING) local real flee_percent = LoadReal(additional_info, key, FLEE_PERCENT) local boolean avoiding_towers = LoadBoolean(additional_info, key, AVOID_TOWERS) local boolean state_retreat = LoadBoolean(additional_info, key, STATE_RETREAT) local real start_strength = LoadReal(additional_info, key, START_STRENGTH)**
> 
> if you add this mechanism , then different Harass groups should can harass different target unit or target player , but now get target usually they are the closest players and should be able to obtain the second closest player

```

 function StartHarass takes integer groupnum, integer harass_target, boolean avoid_towers, real strength_limit, real flee_percent, integer flee_number, real lx, real ly returns nothing
**********
  local integer key = -1
  local real strength = 0
  loop
    exitwhen key >= 0 or i >= 5
    if LoadGroupHandle(additional_info, HARASS_COUNT, i) == null then
      set key = i
    endif
    set i = i + 1
  endloop

**********
  call SaveGroupHandle(additional_info, HARASS_COUNT, key, g)
**********
```
```

function HarassRuning takes integer key, integer ht, unit targ, group harasser returns nothing
**********
     call RemoveSavedHandle(additional_info, HARASS_COUNT, key)  // add all end job
endfunction 

function HarassJob takes integer ht, unit targ, group harasser returns nothing
  local integer i = 0
  local integer key = -1
  loop
    exitwhen key >= 0 or i >= 5
    if LoadGroupHandle(additional_info, HARASS_COUNT, i) == harasser then  //  find key
      set key = i
    endif
    set i = i + 1
  endloop
  if key >= 0 then
    call HarassRuning(key, ht, targ, harasser)
  endif
endfunction
```

use this can let each group runs separately

**Comment by jzy-chitong56** [comment]
not take second closest player


[HARASS.zip](https://github.com/SMUnlimited/AMAI/files/13661085/HARASS.zip)
