### ISSUE TITLE
Why does AMAI 2.6.0 not work with Warcraft 3 v 1.28? 

### ISSUE THREAD

**Issue by Lolasik011** [SMUnlimited/AMAI#20]
AMAI 2.6.0 not work with Warcraft 3 v 1.28.5.7680

**Comment by SMUnlimited** [comment]
AMAI 2.6.0 works with 1.28, even AMAI 2.5.4 still works with 1.28. 

The only reason it might not is if you used the old "AMAI.exe" and haven't done this step from the readme.

> Note: If you want to use the old AMAI.exe to install AMAI to maps you must have run MPQEditor htsize "C:\mymap.w3m" 64 from a commandline to garuantee the AI will be installed correctly.

**Comment by Lolasik011** [comment]
> AMAI 2.6.0 works with 1.28, even AMAI 2.5.4 still works with 1.28.
> 
> The only reason it might not is if you used the old "AMAI.exe" and haven't done this step from the readme.
> 
> > Note: If you want to use the old AMAI.exe to install AMAI to maps you must have run MPQEditor htsize "C:\mymap.w3m" 64 from a commandline to garuantee the AI will be installed correctly.

Can you please explain to me how to install the AMAI correctly?

**Comment by SMUnlimited** [comment]
> Run InstallTFTtoMap from a commandline, to install AMAI to maps 
E.G: After opening a command prompt at the AMAI folder type the following:
**InstallTFTToMap.bat "C:\mymap.w3m"**

**Comment by Lolasik011** [comment]
> > Run InstallTFTtoMap from a commandline, to install AMAI to maps
> 
> E.G: After opening a command prompt at the AMAI folder type the following:
> **InstallTFTToMap.bat "C:\mymap.w3m"**

this does not open a command line

**Comment by SMUnlimited** [comment]
Same problem as #24
