### ISSUE TITLE
Send_Home actions do not have unit control.

### ISSUE THREAD

**Issue by SMUnlimited** [SMUnlimited/AMAI#200]
Seems hero needed to be SEND_HOME but as guard position was not removed it kept going back into the fight even though it needed aid.

**Comment by jzy-chitong56** [comment]
[MICRO_HERO.zip](https://github.com/SMUnlimited/AMAI/files/13663201/MICRO_HERO.zip)
[SEND_HOME.zip](https://github.com/SMUnlimited/AMAI/files/13663202/SEND_HOME.zip)

try my code

**Comment by jzy-chitong56** [comment]
[RESET_HEALTH.zip](https://github.com/SMUnlimited/AMAI/files/13663295/RESET_HEALTH.zip)
