### ISSUE TITLE
language for chinese can not be available

### ISSUE THREAD

**Issue by keamspring** [SMUnlimited/AMAI#21]
i try to repair this problem , but cannot repair it . I think the main problem are loading encoding in Language.txt and the encoding of **.eai . 
please connect me if you wanna repair this problem

**Comment by keamspring** [comment]
when i modify the Chinese encoding to utf8 in Language.txt  ,it worked and seems that generate the correct common.ai in IDEA debugging , but failed when I execute makeall.bat. 
can u tell me how the function INCLUDETABLE  read file by encoding?

**Comment by keamspring** [comment]
the reason has be found. The encoding of Chinese Language package is utf8 , but the encoding in Language.txt is iso-8859-1. 
when I modify the encoding to utf8 in Language.txt and run "perl ejass.pl common.eai TFT VER:TFT > Scripts\TFT\common.ai" in MY Intellij IDEA (develop tools).
It seems that the correct common.ai file was generated. ( I will check it by run Warcraft3 later)
But another question occurred . When I run "MakeTFT.bat" in windows10 cmd ,  some error message occurred:  utf8 "\x80" does not map to Unicode at ejass.pl line 161, <TABLE> line 122. utf8 "\x81" does not map to Unicode at ejass.pl line 161, <TABLE> line 123.
May be the default encoding in window10 cmd is GBK (via my localTimeZone of Beijing)?

**Comment by keamspring** [comment]
another quesion : what the StandardCharTable is generated? Is there all of chars all of Languages?

**Comment by keamspring** [comment]
There is some question in  CommandTrans.txt and Strategy.txt in Chinese language package, I will repair it later.

**Comment by SMUnlimited** [comment]
StandardCharTable is working around issues with strings in AI code as natives don't work correctly in this setting, only really used for some of the programmable chatting conditions I believe. You hopefully should be able to ignore it for the translation.

Yes the errors you have seem to be missing/corrupt characters in the Strategy.txt file. Fix those and you should be able to progress.

`Scripts\TFT\common.ai:13575: Invalid escape character sequence
Scripts\TFT\common.ai:13592: Invalid escape character sequence
Scripts\TFT\common.ai:13614: Invalid escape character sequence
Scripts\TFT\common.ai:13614: Invalid escape character sequence
Scripts\TFT\common.ai failed with 4 errors
Parse failed: 4 errors total
Parse successful:     4180 lines: common.j
Scripts\TFT\common.ai:13575: 'x' is not a valid string escape character
Scripts\TFT\common.ai:13592: 'x' is not a valid string escape character
Scripts\TFT\common.ai:13614: 'x' is not a valid string escape character`

![image](https://user-images.githubusercontent.com/5180431/90337070-ee779b00-dfd7-11ea-9ad7-413c0b212433.png)

**Comment by keamspring** [comment]
I has resolved this problem,  for this pull request can be merged :https://github.com/SMUnlimited/AMAI/pull/23

**Comment by SMUnlimited** [comment]
Thanks @keamspring all merged
