### ISSUE TITLE
Undead lumber mining gets starved with multiple towns

### ISSUE THREAD

**Issue by SMUnlimited** [SMUnlimited/AMAI#213]
The ghouls attempt to harvest from a town that has no necropolis, then hike miles to return the wood.

Ultimately results in whole game they starved for wood due to inefficient wood harvesting. 

Possibly related to town defense as all ghouls hike back to the town without necropolis to defend it.

**Comment by jzy-chitong56** [comment]
now **send home job** can get unit traveling to random bases
But still will issue harvesting orders to them
`_call CreateDebugTag("SEND_HOME harvest lumber", 10, u, 3.00, 1.50)_`

Maybe next time check nearby bases before send out harvesting orders.
