### ISSUE TITLE
Evaluate whether the new version has weakened AI

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#219]
Received some feedback

The new version is not as good as 3.10C, and the corresponding version should be 3.0.1 or 3.1.1 or 2.54

For example, AI will no longer suppress human players or interfere with human players in attack creep up leveling , not Double line operation , not attack creep up leveling , Low desire to attack

--------------------------------------------------------------------------------------
Just like send injured units to different bases, I'm worried that some of my modifications may have had a negative impact. Disrupted the previous logic

**Comment by SMUnlimited** [comment]
I don't think there has been any direct changes to the willingness to attack in your merged changes. The strengths of creeps will be the same now as they were then. Profile randomness could explain those differences in desire to attack, perhaps unlucky and got all profiles that dislike to attack.

**Comment by jzy-chitong56** [comment]
Is that because the configuration parameters for the added professional player profiles were not set well, but the newly added profiles diluted the probability of selecting previous profiles, resulting in an overall weakening?

**Comment by SMUnlimited** [comment]
I'm seeing good levels of aggression so its not a problem in master.
