### ISSUE TITLE
 How is this going

### ISSUE THREAD

**Issue by jackerleowang** [SMUnlimited/AMAI#22]
![AMAI](https://user-images.githubusercontent.com/54178143/90037269-99493a00-dcf6-11ea-8f5a-6ff847eb56c5.png)

**Comment by SMUnlimited** [comment]
Blizzard.j file is not in the "scripts/" folder so you won't be able to order AI's around. 

I don't recommend you use "AMAI.exe" due to the issues listed in the readme, use the InstallTFTToMap.bat or InstallTFTtoDir.pl instead 

> Note: If you want to use the old AMAI.exe to install AMAI to maps you must have run MPQEditor htsize "C:\mymap.w3m" 64 from a commandline to guarantee the AI will be installed correctly.

**Comment by jackerleowang** [comment]
Sorry.I will not operate.

**Comment by jackerleowang** [comment]
Looking forward to your update to solve this problem.

**Comment by keamspring** [comment]
At first you must run "MakeAll.bat" to generate "Blizzard.j" .

**Comment by jackerleowang** [comment]
![20200815021235](https://user-images.githubusercontent.com/54178143/90280024-d0595000-de9c-11ea-96ef-1e6f6805c672.png)
Still unable to increase AI

**Comment by SMUnlimited** [comment]
I recommend you re-download one of the releases here: https://github.com/SMUnlimited/AMAI/releases 

You do not need to compile anything if you use one of those.

**Comment by jackerleowang** [comment]
Thank you.
