### ISSUE TITLE
Trace function can optimize

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#220]
1.maybe all non-public functions require an additional tracking report to inform the AI of where the script is currently running

2.When there are too many AI, it is likely that only one AI report can be displayed because there are too many reports ， but some report no need show at a time. , like build loop or exp or no job run --- because at this time, we are not focused on checking whether certain functions of the AI are working properly, but on paying attention to which sentence the program is running, making it easier to check where the crash occurred . So now function should check AI num ， important report  use new function 

```
function TraceImportant takes string s returns nothing
	if debugging then
		call UpdateDebugPlayer()
		call DisplayToAllFromPlayer(s, debug_player, false)
	endif
	// Blizzard ai part
	if trace_on then
		call DisplayText(GetAiPlayer(),s)
	endif
endfunction 


function Trace takes string s returns nothing
	if debugging and c_ai_total <= 6 then
		call UpdateDebugPlayer()
		call DisplayToAllFromPlayer(s, debug_player, false)
	endif
	// Blizzard ai part
	if trace_on then
		call DisplayText(GetAiPlayer(),s)
	endif
endfunction 
```

**Comment by SMUnlimited** [comment]
Whether its only 2 players or 24 players its still the same number of logs. Be better to have different categories then turned on by config. Job debugging trace logging is already an example of that as it needs a different switch to turn on. 
You can add multiple debug levels as you need it like that. You would in theory have levels for every functional area then have levels within that but best to make do adhoc.
