### ISSUE TITLE
set town_built[town] = false  effect is not very good

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#221]
StartUnitAM have a set town_built[town] = false 
but racial_expansion should cannot go in StartUnitAM 

now you not send save unit to expansion
maybe can use `exist_town mechanism` set town_built

Because `Forced Harvest`  best effect should use own_town_mine , and `own_town_mine can reset` when` town_built[town]  is  false `
```
function universal_peon_assignment
...........
  if (FoodUsed() <= 20 or GetMinesOwned() < 1 or g <= 2500) and hero_built[3] then  // later stages of the game, AI may not be harvest
    set i = 0
    set T = 0
    loop
      exitwhen i > max_towns or T > 2
      if own_town_mine[i] != null and not CheckExpansionTaken(own_town_mine[i]) then
        call PeonMineCheck(own_town_mine[i])
        set T = T + 1
        call CreateDebugTag("Forced Harvest", 10, own_town_mine[i], 3.00, 1.50)
      endif
      set i = i + 1
    endloop
```

like
![image](https://github.com/SMUnlimited/AMAI/assets/48715223/0fa34be3-1fc7-4daa-9dde-27ea0d39b1a0)

**Comment by SMUnlimited** [comment]
Nothing else i can do here, town logic is hardcoded so its not always certain TownWithMine matches AMAIs own_town variables. They could be somewhere completely different. I've added some extra protection to reduce the chance it is somewhere else entirely.

**Comment by jzy-chitong56** [comment]
```
   if SetProduce(afford_qty,old_id[unitid],town) then
      if town != -1 and unitid == racial_expansion then
        set town_built[town] = false
      endif
```

When the start loc town is demolished, the AI's`FactoryNumberUpdate` - will automatic  construction a new town  on start loc  . so I believe this code can work


------------------------------------------
forced harvest, I have code to handle , but I haven't seen the actual effect yet
