### ISSUE TITLE
Player disconnected feedback

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#224]
some feedback said human player disconnected ， they use China Game platform , A few friends fight against AI together
**The same issue will not occur in the previous AMAI version**

this platform use 1.27a or 1.36.0 crack , and all1.27a embedded with platform APIs
_Mainly used to obtain platform member level, ladder points, and item information purchased in the platform mall , and encapsulated trigger events/conditions/actions_

Feedback suggests that there may be issues with inconsistent timelines and errors between players

The feedback also states that players experience disconnection when they using ZOOM adjustment function, whether it is built-in in BJ or built-in on the platform

I think either cache was used to handle the chat queue
Either some of my code affected the main branch

I suggest you consult HIVE to see if anyone has encountered this issue on Battle.net or other non Chinese platforms

**Comment by jzy-chitong56** [comment]
It may be caused by consistent triggering conditions of map commands

-Zoom

**Comment by SMUnlimited** [comment]
Give this commit https://github.com/SMUnlimited/AMAI/commit/38687e2e89874d9ed1ee5c79f98adbf737a1fc86 a try to see if that fixes it.

**Comment by jzy-chitong56** [comment]
Your master branch also  crash

- war3 1.29.2.2931  
- (24)Emersion v3.0 Standard Melee.w3x
- 11 vs 12 + observer   


Considering that the code did not occur before running

I suspect it was caused by DETECT_DOUBLE_EXP

![image](https://github.com/SMUnlimited/AMAI/assets/48715223/c5b2a1f1-5d3e-4d67-8d4f-e1ec4ee28cc0)

**Comment by SMUnlimited** [comment]
v1.29 is not a safe version to be on as has known issues with AMAI. It will also explain no chat messages as well. Downgrade or upgrade to avoid those issues.

**Comment by jzy-chitong56** [comment]
It is true that the problem cannot be found by checking the code, and it is difficult to find it. However, by disabling some job functions, the game can run until the end without crashing. Therefore, I have been trying to locate which line of code has the problem in the past few months, and I always believe that it is not a problem with the game, but an error in the code itself

I have run games on 1.36 before and game disappear directly, so I think changing versions cannot avoid it

Another issue is that at 1.36, while the game may run continuously in the foreground without causing any lag, I have tested that I usually switch to the desktop to check the code (only one display), and when I switch back to the game, the game will become 0FPS

**Comment by jzy-chitong56** [comment]
chinese

Regular chat cannot display Chinese characters, only letters and numbers can be displayed
But the Strategy.txt is not affected
![image](https://github.com/SMUnlimited/AMAI/assets/48715223/0b0ced3b-a16e-49f9-a0d1-463c217b44c9)

**Comment by jzy-chitong56** [comment]
zoom Numerical recording should use arrays, with each player recording independently

**Comment by sil-let** [comment]
So has this problem  been solved ？I still encountered this problem when I try to play with my friends on LAN.
