### ISSUE TITLE
global strategy block excessive harshness

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#226]
Firstly, this restriction still does not apply to TFT
_I did not test the REF version_

Two , current situation is that the AI built barracks too late, and the logging fields have been built but the barracks have not been put down yet

[8ea72d3](https://github.com/SMUnlimited/AMAI/commit/8ea72d37ef2effbe1702addf5093ac5b89070dd6)

**Comment by SMUnlimited** [comment]
Should now build in expected order https://github.com/SMUnlimited/AMAI/commit/26769610fd06becd25b17e653e3d211911746590
