### ISSUE TITLE
Upkeep.txt use Mines needed restrictions unreasonable

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#227]
1. Conflict between restrictions and unconventional maps , like the map set max food > 100
2. If the map is large or players, but there are few teams ，not ffa , like 12 v 12 , 6 v 6, the restrictions are also unreasonable
3. If there are many available gold mines and mines num > player num， the restrictions are also unreasonable
4. In some 1v1 or situations with fewer players, it may be easier to win by breaking through the population without considering expansion

Perhaps this **Mines needed** can be written into the personality of the file

**Comment by SMUnlimited** [comment]
1. Always requires AI modifications as upkeep limits are not available to ai scripts.
2. If you have a team and they have expanded that is fair but not straight forward.
3. This is just making sure they save up more before breaking the limit as its alot less resources to play with. If more than enough mines then breaking the limit is fine. 
4. Added a random element.
