### ISSUE TITLE
gold_mines_ids bug

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#228]
I think the original intention of this variable is to record `special racial gold mines`, rather than `NEUTRAL gold mines`

```
#INCLUDETABLE <$VER$\StandardUnits.txt> #COND "%4" =~ /\bmine\b/
    set gold_mines_ids[gold_mine_ids_size] = '%2'
    set gold_mine_ids_size = gold_mine_ids_size + 1
#ENDINCLUDE
```

now have a bug 
```
UNDEAD_MINE	ugol	UNDEAD	expansion
ELF_MINE	egol	ELF	mine
GOLD_MINE	ngol	NEUTRAL	mine
```

- UD MINE not use mine , it use expansion , so it can not record UD ， but record neutral mine, I know there is a way to use commas to add definitions, but I'm not sure if this writing will work correctly
- NEUTRAL GOLD use mine too , so `CheckDoubleExpansionsClaimedInArea `  `double_expansion_ally_present`  forever effective , then AI will continuously triggering the cancellation of all bases , resulting base upgradation， training and expansion being unable to proceed
```
     if double_expansion_ally_present then
        call IssueImmediateOrderById(u, order_cancel)
        call Trace("Ally double expansion detected")
      endif
```

`UNDEAD_MINE	ugol	UNDEAD	expansion,mine` can use
and ， you need fix ROC  TFT  REF

**Comment by SMUnlimited** [comment]
Good spot, fixed

**Comment by jzy-chitong56** [comment]
NO  Not fixed

only ud have race_uses_mine_expansion , other race the race_uses_mine_expansion  is false , so they can not record ugol

so should use 
`UNDEAD_MINE	ugol	UNDEAD	expansion,mine`

```
    if race_uses_mine_expansion then	// To get undead type mine systems
      set racial_goldmine[minearray] = old_id[racial_expansion]
      set minearray = minearray + 1
      set gold_mines_ids[gold_mine_ids_size] = old_id[racial_expansion]
      set gold_mine_ids_size = gold_mine_ids_size + 1
    endif
```

---------------------------------------------------------------------------------------------------
see `CheckDoubleExpansionsClaimedInArea` 
`IsUnitGoldMine(u)` --  IsPlayerAlly(ai_player, GetOwningPlayer(u))  -- Player(PLAYER_NEUTRAL_PASSIVE) and ai_player is ALLY, so double_expansion_ally_present is true -- **so **gold_mines_ids** cannot record `NEUTRAL mine`** 

` IsUnitType(u, UNIT_TYPE_TOWNHALL)` --  IsPlayerAlly(ai_player, GetOwningPlayer(u)) -- -- ai_player and ai_player is ALLY, so double_expansion_ally_present is true , **CheckDoubleExpansionsClaimedInArea need input ru , and first call GroupRemoveUnit(g,ru)**

so double_expansion_ally_present will always be true
CheckDoubleExpansion  -- always  ` call IssueImmediateOrderById(u, order_cancel)`


```
CheckDoubleExpansionsClaimedInArea 
if IsUnitGoldMine(u) then
      if GetOwningPlayer(u) != ai_player and GetOwningPlayer(u) != Player(PLAYER_NEUTRAL_PASSIVE) then
        set claimedMines = claimedMines + 1
      endif
      if IsPlayerAlly(ai_player, GetOwningPlayer(u)) then
        set double_expansion_ally_present = true
      else
        set double_expansion_target = u
      endif
      set minecount = minecount + 1
    endif
    if IsUnitType(u, UNIT_TYPE_TOWNHALL) then
      if GetOwningPlayer(u) != ai_player and GetOwningPlayer(u) != Player(PLAYER_NEUTRAL_PASSIVE) then
        set claimedMines = claimedMines + 1
      endif
      if IsPlayerAlly(ai_player, GetOwningPlayer(u)) then
        set double_expansion_ally_present = true
      else
        set double_expansion_target = u
        set double_expansion_enemy_present = true
      endif
    endif

```
