### ISSUE TITLE
The problem of excessive construction intervals -- ANCIENT_WAR 

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#229]
The problem is not with BR
After BR runs, the interval between the next cycle is too long
It took a long time to see `t`
Continuing construction after BR is invalid as there may be no available WISP available anymore
Perhaps it is necessary to send a construction command after the completion of BR

```
    if unitid == ANCIENT_WAR and racial_rushcreep < 0 then
      call DisplayTimedTextToPlayer(Player(0),0,0,15,"t")
    endif
    if unitid == racial_rushcreep then
      if CreepsOnMap() and not towerrush then
	    call DisplayTimedTextToPlayer(Player(0),0,0,15,"a")
            if BuildBRAtCreep() then
	        if afford_qty < 2 then
                        set racial_rushcreep = -1  //just run once
		        call DisplayTimedTextToPlayer(Player(0),0,0,15,"xx")
		        return BUILT_SOME
	        endif
            endif
      endif
      set racial_rushcreep = -1  //just run once
      //return BUILT_SOME
    endif
```

**Comment by SMUnlimited** [comment]
Is this an issue in master as there used to be an erroneous wait between every build action until recently as now its only about every 5 seconds to loop.

**Comment by jzy-chitong56** [comment]
master removed some strategy barracks restriction logic during the repair, so I think you have also encountered this problem before. I think these logic have been working for more than ten years, and it doesn't seem like there is a problem. The problem should be elsewhere,Perhaps we can add back these logics and fix them in other ways?
