### ISSUE TITLE
OptimizeAll.bat -- My submission was not merged correctly

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#230]
now **MakeOpt$ver$.bat** just call **MakeOptVER.bat**

MakeOptVER.bat **Optimized from the beginning**

if you set to run  ` OptimizeAll.bat`  first in the workflow
you will see Error reporting
Because this has not run any other compilations and the script file has not been created yet
`perl Optimize.pl -b Scripts\XXXX `  all cannot find file
opt not `call ForwardsCompat.bat`

```
perl Optimize.pl %VER%\common.j Scripts\%VER%\common.ai -l %VER%\Races.txt Scripts\%VER%\$2
perl Optimize.pl -b Scripts\Blizzard_%VER%.j
```

only maketft have `call TFT/Inherit.bat` , opttft and vsaitft not call

------------------------------------------
Additionally, I have included some Chinese translation adjustments in my submission... It seems that you have overlooked them
EMMM

**Comment by SMUnlimited** [comment]
Optimise not designed to make the scripts as well, has to be run seperately after the make.
