### ISSUE TITLE
TFT BuildSequence.ai some distraction_group error

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#235]
fix distraction_group  not correctly applied to TFT BuildSequence.ai

Maybe ROC didn't either

**Comment by jzy-chitong56** [comment]
https://github.com/SMUnlimited/AMAI/pull/202
here should be have fix

**Comment by SMUnlimited** [comment]
Can't see any issues, distraction groups all correct, slightly different from reforged in numbers but the numbers are valid.

**Comment by jzy-chitong56** [comment]
In fact, I think there's a problem with the numbers

the difference in numbers stems from a certain repair. If the numbers are correct, why would they be modified?

**Comment by SMUnlimited** [comment]
The number for distractions just needs to not conflict with other global harass groups. The number used can be whatever group the strategy wants otherwise.
