### ISSUE TITLE
CommonSleepUntilTargetDeadAM bug

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#236]
```
CommonSleepUntilTargetDeadAM
..........
    exitwhen town_threat_break and town_threatened and most_threatened_town >= 0 and town_threat[most_threatened_town] >= teleport_low_threat and not desperation_assault
    exitwhen break_attack and not desperation_assault
```

exitwhen town_threat_break and` town_threatened `and most_threatened_town >= 0 and town_threat[most_threatened_town] >= teleport_low_threat and not desperation_assault

but occasionally ,  not returning home for rescue when the attacking target has not disappeared and the retreat has not been triggered

not check target is null ??
```
      call AttackMoveKill(target)
      set lastcaptainx = GetUnitX(target)
      set lastcaptainy = GetUnitY(target)
      if (c_ally_total > 0 and GetAllianceTarget() == target) then
        call CreateDebugTag("Reform until ally dead", 10, target, 1.00, 0.80)
      else
        call CreateDebugTag("Reform until target dead", 10, target, 1.00, 0.80)
      endif
```

call Sleep(2 * sleep_multiplier) and call FormGroupAM(2) , sleep too long ?

-------------------------------------------------------------------
change , check ally

```
CommonSleepUntilTargetDeadAM
..........
    if **IsPlayerAlly(ai_player, GetOwningPlayer(target))** or not UnitAlive(target) or (UnitInvis(target) and not IsUnitDetected(target, ai_player)) then
      set g = CreateGroup()
      call GroupEnumUnitsInRange(g,GetUnitX(target), GetUnitY(target),battle_radius,null)
      set g = SelectByEnemy(g,ai_player, true)
      set g = SelectByAlive(g,true)
      set g = SelectByHidden(g,false)
      if not UnitAlive(target) or UnitInvis(target) then
        set g = SelectByVisible(g,ai_player,true)  // to find enemies that ai has noticed
      endif
      if iscreeping then
        set g = SelectByPlayer(g, Player(PLAYER_NEUTRAL_AGGRESSIVE), true)  // if creeping and unit invisible see if any other creeps targetable
      endif
      set target = FirstOfGroup(g)
      call DestroyGroup(g)
      exitwhen target == null
    endif

```

**Comment by SMUnlimited** [comment]
This is mostly intended. CaptainControl retreats too easily so we override it to force them to stay put. If its not dealing with real threats maybe needs a tweak somewhere in one of the settings.

The sleep is likely there to prevent cases of infinite loops without any sleep which will kill performance. Also not enough sleep can drop performance as well.

**Comment by jzy-chitong56** [comment]
You may need to test other AI to discover the problem, as official AI is not challenging and AMAI VS AMAI seems to not be able to detect the problem

When there is a problem, you will see the base being attacked, but the CREEP target has not been cleared, and the army will not go back

[2.zip](https://github.com/SMUnlimited/AMAI/files/14159422/2.zip)

**Comment by jzy-chitong56** [comment]
lastcaptainx and lastcaptainy Lack of default recovery mechanism， so SleepInCombatAM 
```
SleepInCombatAM It runs every time `TeleportCaptain`
Does this align with the original design intention？？
..................................
    if (lastcaptainx != 0 and lastcaptainy != 0 and not CaptainIsEmpty()) then
      call TeleportCaptain(lastcaptainx, lastcaptainy)
    endif
```

**Comment by SMUnlimited** [comment]
Its all about priority. The current attack may cause more damage than falling back to defend. SleepInCombat triggers once the current attack is done, don't move onto another.  The lastcaptainx is an attempt to keep the army around the last attack target to collect any items.
