### ISSUE TITLE
Problema sobre el jugador número 14 (IA)

### ISSUE THREAD

**Issue by CristhianWcF** [SMUnlimited/AMAI#238]
-He notado que en los mapas de 24 jugadores, al momento de estar asignando los rivales y entrar a jugar, la IA número 14 estuviera aliada con las unidades hostiles del mapa (trolls, ogros, etc) porque van a su ubicación a atacar pero no atacan y las unidades hostiles tampoco lo atacan, se quedan ahí ambos quietos.
También he notado que es imposible hacer equipo o que la IA número 14 haga equipo con otra IA porque al establecer los equipos y entrar a jugar esa IA si o si te marcará como enemigo.
-Al referirme con la IA número 14 no me refiero que en la sección equipo sea el número 14, sino que al estar agregando jugadores, el jugador número 14 (IA) tiene el problema que había comentado.
![Screenshot_20240201-214243~2](https://github.com/SMUnlimited/AMAI/assets/157925717/cce7506a-262c-43e3-b776-66ae936163e4)

**Comment by jzy-chitong56** [comment]
In some 24 player maps, individual players may indeed be born at the wrong starting point, such as sharing a starting point with other players
But the reason is unknown
And perhaps it was caused by the same reason

**Comment by SMUnlimited** [comment]
Hey @CristhianWcF Which map are you using? Did you install classic or reforged AMAI? Are you using the latest AMAI version?

**Comment by CristhianWcF** [comment]
> Ey@CristhianWcF¿Qué mapa estás usando? ¿Instalaste AMAI clásico o reformado? ¿Estás utilizando la última versión de AMAI?

Estoy usando el AMAI clásico y si es la última versión.
Posdata: Su IA me ha devuelto las ganas de jugar warcraft 3 otra vez, gracias.

**Comment by SMUnlimited** [comment]
Thanks found and fixed in master.
