### ISSUE TITLE
AMAI 2.6.0 not working with 1.29

### ISSUE THREAD

**Issue by Purouwu** [SMUnlimited/AMAI#24]
When I try to play custom games, the menu where to choose the number of computers, race, teams and color is missing. When I try to start, it just gives a red error and returns to the previous menu. The AMAI 2 folder is AMAI 2.6.0, the one without number is 2.54, which works but it has some bugs, like when the computers says something in chat it's just blank and the number of strategies menu to choose from is from 0-9, when some races have up to 15 strategies. Can you please make a video tutorial on how to install AMAI 2.6.0 and later?

https://user-images.githubusercontent.com/62399556/104109511-5f955300-52d7-11eb-8ee5-0dcd3cfca083.mp4

**Comment by SMUnlimited** [comment]
It suggests the scripts are not installed correctly. 

Usual issue is caused by using the old AMAI.exe. You can fix by running from a command line the below on the maps first

`MPQEditor htsize "C:\mymap.w3m" 64` which allows the map to correctly insert new files. 

If you do not run this command or do not use the better script as in the readme, the maps will only put in part of the amai files which can corrupt the map. 

Easy way to confirm you can open the map using the bundled MPQEditor and if its installed corruptly you should see all the 4 race.ai scripts, the common.ai script and the blizzard.j script. If any of those are missing it hasn't installed correctly.

**Comment by Purouwu** [comment]
> Usual issue is caused by using the old AMAI.exe. You can fix by running from a command line the below on the maps first
> 
> `MPQEditor htsize "C:\mymap.w3m" 64` which allows the map to correctly insert new files.

How do I run the command line?

**Comment by SMUnlimited** [comment]
On windows 10, open windows Start Menu, then type "cmd" then press enter.

Alternatively using MPQEditor you can open the map as an MPQ.

Click set max file count to 64 to allow more files to be added to the map correctly.
![image](https://user-images.githubusercontent.com/5180431/104128429-594ab980-535f-11eb-89b7-05cef83ca451.png)

If the scripts are installed in the map correctly there should be a scripts folder shown next to the _Locales folder containing all the files you posted above.

**Comment by Purouwu** [comment]
> On windows 10, open windows Start Menu, then type "cmd" then press enter.
> 
> Alternatively using MPQEditor you can open the map as an MPQ.
> 
> Click set max file count to 64 to allow more files to be added to the map correctly.
> ![image](https://user-images.githubusercontent.com/5180431/104128429-594ab980-535f-11eb-89b7-05cef83ca451.png)
> 
> If the scripts are installed in the map correctly there should be a scripts folder shown next to the _Locales folder containing all the files you posted above.

I used MPQEditor and it was already 64 max files. When I use AMAI.exe, it just creates a folder named "Scripts" and inside it's the race.ai scripts

**Comment by SMUnlimited** [comment]
If the "scripts" folder shown in MPQEditor contains all the following it should then be working.
![image](https://user-images.githubusercontent.com/5180431/104137710-bdd53b00-5396-11eb-8396-d0ff7c1b3260.png) 

If not you might need to share the map file so i can see if there is anything else odd that might have happened?

**Comment by Purouwu** [comment]
> If the "scripts" folder shown in MPQEditor contains all the following it should then be working.
> ![image](https://user-images.githubusercontent.com/5180431/104137710-bdd53b00-5396-11eb-8396-d0ff7c1b3260.png)
> 
> If not you might need to share the map file so i can see if there is anything else odd that might have happened?
Yes, the "scripts" folder contains the race.ai files. Here is the map. I had to use winrar because w3x is not supported.


[(2)BanditRidge.zip](https://github.com/SMUnlimited/AMAI/files/5794296/2.BanditRidge.zip)

**Comment by SMUnlimited** [comment]
Strange all the files in the script folder of the map are empty files (0 bytes) which would explain why warcraft just errors out. I'm not sure how what could have caused that to happen. 

I re-ran the following InstallTFTtoMap.bat to reinstall, and then the map seems to run up fine🤷 
![image](https://user-images.githubusercontent.com/5180431/104241537-c17bc700-5455-11eb-98a4-290dab5fe75c.png)

**Comment by Purouwu** [comment]
> Strange all the files in the script folder of the map are empty files (0 bytes) which would explain why warcraft just errors out. I'm not sure how what could have caused that to happen.
> 
> I re-ran the following InstallTFTtoMap.bat to reinstall, and then the map seems to run up fine🤷
> ![image](https://user-images.githubusercontent.com/5180431/104241537-c17bc700-5455-11eb-98a4-290dab5fe75c.png)

When I run InstallTFTToMap.bat it opens a cmd for 0.5 seconds then closes itself. Is this normal? Or I have to edit the bat file and type something in it? If not, can you please tell me the exact steps you made to install AMAI on the map? 

https://user-images.githubusercontent.com/62399556/104243398-2c82c900-5469-11eb-8253-7fe8bf943a2c.mp4

**Comment by SMUnlimited** [comment]
Looks like your script files are corrupt somehow so I suggest re-downloading the release and confirm the files are not 0 bytes after extraction. 

For the bat file, you need to pass in the map you want install to like I did on the first line of the screenshot above so you can't just double click. 

You can have to open "cmd" prompt (I used windows "powershell" in my pic) first. Navigate to the directory containing the bat script. Then run the command.

**Comment by Purouwu** [comment]
> Looks like your script files are corrupt somehow if they are all 0 bytes on the file system so I suggest re-downloading the release and confirm the files are not 0 bytes after extraction.
> 
> For the bat file, you need to pass in the map you want install to like I did on the first line of the screenshot above so you can't just double click.
> 
> You can have to open "cmd" prompt (I used windows "powershell" in my pic) first. Navigate to the directory containing the bat script. Then run the command.

Yes, the ai files are not 0 bytes anymore, if I run the MakeTFT.bat file it makes them 0 bytes. I used AMAI.exe then InstallTFTToMap.bat, the ai files are no longer 0 bytes but I still can't play, the race, team, color menu is still missing.
![Capture](https://user-images.githubusercontent.com/62399556/104245409-e29be200-546c-11eb-9f62-3ad8fcfddb9e.PNG)
![Capture1](https://user-images.githubusercontent.com/62399556/104245463-fe06ed00-546c-11eb-8297-320b1b49dccb.PNG)
![Screenshot (152)](https://user-images.githubusercontent.com/62399556/104245474-019a7400-546d-11eb-874b-e5ca0947ce29.png)

**Comment by SMUnlimited** [comment]
You don't need to use the makeTFT.bat unless you are making changes to AMAI's code. Just use the pre-built copies. 
And avoid using the AMAI.exe entirely if you happy to use the InstallTFTToMap.bat. Its alot safer.
I wonder if you should consider running installTFTToMap as an administrator if you have not already? 
If still not working after doing all that can you reshare the latest copy of the map you have?

**Comment by Purouwu** [comment]
> You don't need to use the makeTFT.bat unless you are making changes to AMAI's code. Just use the pre-built copies.
> And avoid using the AMAI.exe entirely if you happy to use the InstallTFTToMap.bat. Its alot safer.
> I wonder if you should consider running installTFTToMap as an administrator if you have not already?
> If still not working after doing all that can you reshare the latest copy of the map you have?

I reinstalled AMAI from github, only ran InstallTFTToMap.bat in powershell with administrator rights, but the error is still there.
Here is the map that I used InstallTFTToMap.bat on: 
[(2)BanditRidge.zip](https://github.com/SMUnlimited/AMAI/files/5800513/2.BanditRidge.zip)
Here is the original map:
[(2)BanditRidge.zip](https://github.com/SMUnlimited/AMAI/files/5800515/2.BanditRidge.zip)

**Comment by Lolasik011** [comment]
By the way, I have exactly the same problem...

**Comment by Purouwu** [comment]
> By the way, I have exactly the same problem...

:(

**Comment by SMUnlimited** [comment]
Just loaded up the map you sent just fine. This suggests there is some sort of compatibility problem with 1.29 war3 for AMAI 2.6 as i'm on 1.32 war3 and the map you sent worked just fine.

**Comment by Purouwu** [comment]
> Just loaded up the map you sent just fine. This suggests there is some sort of compatibility problem with 1.29 war3 for AMAI 2.6 as i'm on 1.32 war3 and the map you sent worked and loaded fine.

So AMAI 2.6.0 is for reforged only? I only have the old classic warcraft.

**Comment by SMUnlimited** [comment]
Not the intention for that version....

Think i have an idea what might be the problem. Can you try out this version and see if that fixes the problem? 
[AMAI2.6.1test.zip](https://github.com/SMUnlimited/AMAI/files/5803930/AMAI2.6.1test.zip)

**Comment by Lolasik011** [comment]
> Not the intention for that version....
> 
> Think i have an idea what might be the problem. Can you try out this version and see if that fixes the problem?
> [AMAI2.6.1test.zip](https://github.com/SMUnlimited/AMAI/files/5803930/AMAI2.6.1test.zip)

Everything works for me

**Comment by Purouwu** [comment]
> Not the intention for that version....
> 
> Think i have an idea what might be the problem. Can you try out this version and see if that fixes the problem?
> [AMAI2.6.1test.zip](https://github.com/SMUnlimited/AMAI/files/5803930/AMAI2.6.1test.zip)

It works, but it seems more buggy now, my ally doesn't show me the strategies when I tell him to and some other. What is the difference between this version and AMAI 2.6.0 and AMAI 2.5.4?

**Comment by SMUnlimited** [comment]
2.6.0 doesn't fix anything like that so those might still be genuine bugs. The commander interface hasn't had much love in a long time. 

In terms of chat bugs what language are you playing on?

**Comment by Purouwu** [comment]
> 2.6.0 doesn't fix anything like that so those might still be genuine bugs. The commander interface hasn't had much love in a long time.
> 
> In terms of chat bugs what language are you playing on?

I play in english. The bug is that I see the computer's name trying to say something, but there's nothing after the ":". It's like "[AMAI]Aaargh:". It's just the name and nothing else. It doesn't happen everytime, but sometimes it does.

**Comment by SMUnlimited** [comment]
The chat bug might be an issue with v1.29 of warcraft 3 according to changelog below which restricted the cache used by the language translations but I'm not sure. If you can somehow get 1.29.1/2 that might fix those issues.
> https://liquipedia.net/warcraft/Patch_1.29.1 - Hashtable storage limit is removed.
> Game cache mission key limit is removed.

All I can verify on my end is chat seems to work fine in 1.27 and 1.32 with 2.6.1.

**Comment by Purouwu** [comment]
> The chat bug might be an issue with v1.29 of warcraft 3 according to changelog below which restricted the cache used by the language translations but I'm not sure. If you can somehow get 1.29.1/2 that might fix those issues.
> 
> > https://liquipedia.net/warcraft/Patch_1.29.1 - Hashtable storage limit is removed.
> > Game cache mission key limit is removed.
> 
> All I can verify on my end is chat seems to work fine in 1.27 and 1.32 with 2.6.1.

Okay. Can you please tell me the difference between AMAI 2.54 and AMAI 2.6.1?

**Comment by SMUnlimited** [comment]
That is available here: https://github.com/SMUnlimited/AMAI/blob/2.6.x/CHANGELOG.md

**Comment by Purouwu** [comment]
> The chat bug might be an issue with v1.29 of warcraft 3 according to changelog below which restricted the cache used by the language translations but I'm not sure. If you can somehow get 1.29.1/2 that might fix those issues.
> 
> > https://liquipedia.net/warcraft/Patch_1.29.1 - Hashtable storage limit is removed.
> > Game cache mission key limit is removed.
> 
> All I can verify on my end is chat seems to work fine in 1.27 and 1.32 with 2.6.1.

I downloaded 1.29.2 but the computer still doesn't say anything :/

**Comment by SMUnlimited** [comment]
Bit of a pain though as that sounded most likely to be relevant. Whatever the problem is it sounds like a bug in warcraft by the fact that both older versions and newer versions work. 

One other thought, make sure you stick to the original colours for the players. The new colours for the additional players above 12 might cause issues in this version as that wasn't fixed until 3.00.

You could keep trying different versions. E.g 1.28 as Lolasik011 said everything was working there with 2.6.1. Alternatively go the other way trying 1.30,  1.31.
I may have to add a warning that something in 1.29 and whatever other version numbers you try and fail appears to break the AMAI chat.

**Comment by Coaintelligence** [comment]
> 听起来有点痛苦，但听起来很可能是相关的。不管是什么问题，老版本和新版本都可以工作，这听起来像是魔兽中的错误。
> 
> 另一个想法是，请确保您坚持播放器的原始颜色。12岁以上的其他玩家的新颜色可能会在此版本中引起问题，因为该问题要到3.00才能修复。
> 
> 您可以继续尝试其他版本。例如1.28，就像Lolasik011所说的那样，一切都在2.6.1下运行。或者，尝试以其他方式尝试1.30、1.31。
> 我可能需要添加一条警告，指出1.29中的某些内容以及您尝试失败的任何其他版本号都可能破坏AMAI聊天。

非常感谢！

**Comment by starmandeluxe** [comment]
Just adding my experience if it helps anyone, but I had the same problem and solved it by using an older version of AMAI (AMAI2.54PE). Works great now. Good luck!
