### ISSUE TITLE
ApplyChatVars bug at other lang

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#245]
on chinese , we use `。 ， `  and Chinese characters , not use  `, .`
so ApplyChatVars unable to recognize
I first send` chat_list[rand] + "n你好吗？，" `, Normal display
but when go `ApplyChatVars `, just show letter
```
   if chat == C_Greet then
        if (HaveStoredInteger(amaiCache, Int2Str(GREETINGS_NUM), Int2Str(i))) then
          set chat_greet_count = GetStoredInteger(amaiCache, Int2Str(GREETINGS_NUM), Int2Str(i)) 
        endif    
        if chat_greet_count < 6 then
            //call DisplayToAllFromPlayer("GREET" + Int2Str(chat_greet_count), GetAiPlayer(), false)
            call StoreInteger(amaiCache, Int2Str(GREETINGS_NUM), Int2Str(i), chat_greet_count + 1 )
            //call SyncStoredInteger(amaiCache, Int2Str(GREETINGS_NUM), Int2Str(GREETINGS_NUM))
            call DisplayTimedTextToPlayer(GetLocalPlayer(),0,0,15,chat_list[rand] + "n你好吗？，")                   -----1
            call DisplayToPlayer(ApplyChatVars(chat_list[rand]), p, important)                                        -----2
        endif
      elseif immediate then
        call DisplayToPlayer(ApplyChatVars(chat_list[rand]), p, important)
      else
        call QueueChat(ApplyChatVars(chat_list[rand]), p, important)
      endif
```

![image](https://github.com/SMUnlimited/AMAI/assets/48715223/e30fe287-9f56-4a48-a254-e8131581bfae)

Test found that it is not related to the file

![image](https://github.com/SMUnlimited/AMAI/assets/48715223/86136e38-ef62-492c-8dbc-400dbe18e32d)

**Comment by SMUnlimited** [comment]
This will be related to the LookupCT function and the character table as it parses the text to substitute with realtime information. In this case its appearing to be matching latin characters it shouldn't be.

**Comment by jzy-chitong56** [comment]
I'm not sure where the problem is caused, but it's normal in my branch. It may have been caused by me modifying the compiled com.ai file. However, the previous modification was that the text could be displayed, but it was garbled. Now it has become impossible to display it, and your modifications cannot completely solve the problem. If the text contains letters, there will still be images. Perhaps we need to test the situation of running it directly after compilation without making any changes, See if it's normal
