### ISSUE TITLE
GetExpFoe have a build exp bug

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#246]
Classic Map `TR` , The most famous one is that the CREEP at the entrance of the birthplace is very close to the CREEP at the gold mine
I found that AI often builds gold mines while CREEP is still alive , So conducted some tests

In the first image, you will find that both CREEP locations are recorded by `GetExpFoeGroup` ， so we get  5 or 6 num creep , _expansion_radius is 1000 , if cannot find creep , expansion_radius wiil up to 1500_ , So the two CREEP locations will definitely be recorded

And then the question arises, Players will definitely attack the small dots in front of their homes before expanding
When the small CREEP corpse in front of the door disappears, this unit will definitely become `null`
`So in expansion_creeps [i], there are several null units` ， and `GetExpFoe` Seems to be disturbed by `null’ units , give report in Figure 2 appears( you can see my report code)

Suspect that the problem lies in `CopyGroup` ， I don't know ,  there should be not any problems here -- small dots in front unit is 4 and 5 ,  `CopyGroup`  should have 0~3 unit , `FirstOfGroup(current_expansion_creeps) cannot is null` , Because the order has not changed

`It will only be triggered when the mine creep unit is still alive , but the creep unit in front of the door dies`
I tested your main branch three times before it appeared. It's best for two players to be at the best distance and not interfere with each other. Please disable the militia expansion 

**Perhaps expansion_radius should be restored to 650 instead of setting it to 1000. Use CheckCreepsByradius to handle it**

![image](https://github.com/SMUnlimited/AMAI/assets/48715223/647e440a-0b17-444d-aa2c-af81306b86ad)
![image](https://github.com/SMUnlimited/AMAI/assets/48715223/3ed3b1d3-2570-49e0-a683-6a888773e929)

```
function GetExpFoe takes unit u returns unit
  local group g = null
  local location l = GetUnitLoc(current_expansion)
  //call Trace("Copy group")
  set g = CopyGroup(current_expansion_creeps,g)
  if FirstOfGroup(current_expansion_creeps) == null then
    call DisplayTimedTextToPlayer(Player(0),0,0,15,"0")
  endif
  if FirstOfGroup(g) == null then
    call DisplayTimedTextToPlayer(Player(0),0,0,15,"0.0")
  endif
  set g = SelectByAlive(g, true)
  if FirstOfGroup(current_expansion_creeps) == null then
    call DisplayTimedTextToPlayer(Player(0),0,0,15,"0.00")
  endif
  if FirstOfGroup(g) == null then
    call DisplayTimedTextToPlayer(Player(0),0,0,15,"0.000")
  endif
  set u = GetNearestOfGroup(u, g, l)
  call RemoveLocation(l)
  set l = null
  call DestroyGroup(g)
  set g = null
  //call Trace("Have a foe")
  return u
endfunction

```

fix
```
function GetExpFoe takes unit u returns unit
  local group g = null
  local location l = GetUnitLoc(current_expansion)
  //call Trace("Copy group")
  set g = CopyGroup(current_expansion_creeps,g)
  set g = SelectByAlive(g, true)
  if FirstOfGroup(g) == null then
    set g = CheckCreepsByRadius(g, current_expansion, expansion_radius)
  endif
  set u = GetNearestOfGroup(u, g, l)
  call RemoveLocation(l)
  set l = null
  call DestroyGroup(g)
  set g = null
  //call Trace("Have a foe")
  return u
endfunction
```

**Comment by SMUnlimited** [comment]
This is a major issue. As we can't detect or remove null units from a group in AI code as "ForGroup" doesn't work. So we will have to always run another GroupEnum rather than persisting groups long term.

**Comment by jzy-chitong56** [comment]
in CheckCreepsByRadius ，The unit group has been reselected
I don't think it's necessary to make too many changes

But the same problem also occurs in other neutral passive buildings？？

which happened based on the map and is not easy to test. It is best to fix it together，If there is indeed a problem

Happy Chinese New Year
