### ISSUE TITLE
BUILD_EXPANSION arousal interval time

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#255]
You have shortened the interval time for BUILD.EXPANSION

but `ConstructExpansion` arousal interval has not been adjusted yet

`call TQAddUnitJob(2 * sleep_multiplier, BUILD_EXPANSION, 0, expansion_peon)`

Can we also shorten it here

**Comment by jzy-chitong56** [comment]
Because deleted the `cancel` command

The base that has already started construction will not be cancelled anymore
Perhaps it's possible to determine the health value. If it's below 50%, it's still better to send a cancellation

https://www.hiveworkshop.com/threads/advanced-melee-ai.62879/post-3613612

**Comment by SMUnlimited** [comment]
Not necessary as only just started to build so unlikely to be taken so immediately.
