### ISSUE TITLE
I use Chinese vision and the ai talked in map changed to garbled code qaq

### ISSUE THREAD

**Issue by Coaintelligence** [SMUnlimited/AMAI#26]
i tried to connect you on hiveworkshop，when i choose chinese and then i get grabled code in the game。Can you help me？

**Comment by Coaintelligence** [comment]
![FE00EF4F-CB31-46FD-95B5-6A8AC45D1D97](https://user-images.githubusercontent.com/26812631/105652956-8f5a7280-5ef5-11eb-87af-fd30dc657db2.jpeg)
and also the undead build tower more than human and orc

**Comment by SMUnlimited** [comment]
Hi coaintelligence, there is a fix for chinese coming I just haven't had a chance to release it yet.

Mass Towers is a rare bug, but i believe its a hardcoded issue with how warcraft assigns bases.

**Comment by Coaintelligence** [comment]
> 您好coaintelligence，有一个针对中文版本的修复程序，我只是还没有发布它的机会。
> 
> Mass Towers是一个罕见的错误，但我相信它是有关魔兽如何分配基地的硬编码问题。

thanks a lot！can i connect you withemail or other things for bugs？

**Comment by Coaintelligence** [comment]
> Hi coaintelligence, there is a fix for chinese coming I just haven't had a chance to release it yet.
> 
> Mass Towers is a rare bug, but i believe its a hardcoded issue with how warcraft assigns bases.

hey do you have the chance for releasing that version qwq

**Comment by SMUnlimited** [comment]
Done

**Comment by Coaintelligence** [comment]
> 完成了

well，in2.6.1 version and game 1.24e chinese are also incorrect qwq
