### ISSUE TITLE
disconect  game from hive

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#266]
![image](https://github.com/SMUnlimited/AMAI/assets/48715223/e1fb00f3-b270-4235-995d-c9ce16535ae6)

I have received similar reports before

Still the same after deleting BJ

But when I asked him to use your branch map for testing, he angrily left because I said I didn't want to explain the difference between my branch and the official branch

` call FlushStoredInteger(amaiCache, Int2Str(CHAT_LOCK), "lock")`

I suspect it's the problem with this statement. Operating game caching is very dangerous

How about rewriting it directly to -1 and not clearing it out
https://github.com/jzy-chitong56/AMAI/commit/ab88c302add36b3fc55bdef1cc00843ed0b95c92

**Comment by SMUnlimited** [comment]
Confirmed fixed on hive
