### ISSUE TITLE
double expansion kill compensate

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#272]
As you said, now will cancel or even give up some of the expansion

I still believe that the assessment of health can be more precise. Sometimes buildings may not be full of health, but they are indeed built, being trained, researched, or even upgraded, with only repair functions not activated or being repaired

Additionally, when you cancel, the system will compensate for a portion of the construction resources
But when you kill, these construction costs are wasted, and AI may need some compensation

and If there are already other buildings at this time, it may be necessary to avoid `CheckExpansionRebuild`  
Often, some buildings are not completely demolished by the enemy -- Whether intentional or unintentional

**Comment by jzy-chitong56** [comment]
UD and NAGE 
no need set  `mine,hall`

**Comment by SMUnlimited** [comment]
Probrably invalidated from recent fixes
