### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by Eatmahpie** [SMUnlimited/AMAI#28]
Heyo! Thank you for the work put in this.

I am unable to install the bat. file into the files. Whenever I click on it or use the command prompt, it opens and closes almost immediately. (Have 0 programming experience)

**Comment by InnerExam** [comment]
I had the same problem. You have to open windows powershell, you can find it by searching it in the search menu (bottom left). Then type sl (your drive)\(where AMAI is). For example, for me is "sl D:\Downloads\AMAI" without ". Then you type .\InstallTFTToMap.bat or just type install and press tab, it will put itself for you. After you type that, navigate as you did before to find your map. For example, for me it's ".\InstallTFTToMap.bat C:\Users\(your name)\Documents\Warcraft III\Maps". After yoy typed that, you press enter.

**Comment by Purouwu** [comment]
I had the same problem. You have to open windows powershell, you can find it by searching it in the search menu (bottom left). Then type sl (your drive)\(where AMAI is). For example, for me is "sl D:\Downloads\AMAI" without ". Then you type .\InstallTFTToMap.bat or just type install and press tab, it will put itself for you. After you type that, navigate as you did before to find your map. For example, for me it's ".\InstallTFTToMap.bat C:\Users\(your name)\Documents\Warcraft III\Maps". After yoy typed that, you press enter.
