### ISSUE TITLE
The Impact of AI Names with Difficulty Markers on Professional Player Names

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#283]
maybe when AI use Professional Player Names , no need show Difficulty Markers and AMAI Markers (add_tag and add_skill)
or
add new Markers -- add_tag_profession , add_skill_profession , when AI use Professional Player Names , use this check name show Difficulty Markers and AMAI Markers

Because avatar professional players , do not display these Markers , the experience may be more immersive

**Comment by SMUnlimited** [comment]
Out the box it is better to advertise this is AI. Can be configured easily for custom AI games if they want to hide it.
