### ISSUE TITLE
22 AMAI laggy game unplayable

### ISSUE THREAD

**Issue by zsc2tr** [SMUnlimited/AMAI#29]
Got a serious issue here，when my friend and i trying to play 2v22 amai,the game becomes super laggy after 10mins which is the time when units get more and more.Its unpalyable like 1 fps 1 sec.But the original Ai its ok to play.Please do something about it.

**Comment by SMUnlimited** [comment]
May have been fixed by https://github.com/SMUnlimited/AMAI/pull/65

But improvements still need merging and testing in master

**Comment by SMUnlimited** [comment]
Merged improvements to master in https://github.com/SMUnlimited/AMAI/commit/1c8a38788c0eb0fd8641548fa4d8a0ab26e8b282
