### ISSUE TITLE
We put in a fix for 1.29 heroes not learning spells but appears on 1.31.1 tavern heros are still not learning spells.

### ISSUE THREAD

**Issue by SMUnlimited** [SMUnlimited/AMAI#292]
https://www.hiveworkshop.com/threads/advanced-melee-ai.62879/post-3615920

**Comment by jzy-chitong56** [comment]
Indeed, I later discovered that some skill combinations were in the wrong order
You can refer to the repair of my branch

In addition, if a hero is **RemoveGuardPosition**, he will not learn either, depending on whether there is a **job** in progress
