### ISSUE TITLE
SleepUntilTownDefended some bug

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#299]
```
call SetCaptainHome(DEFENSE_CAPTAIN, GetLocationX(town_loc[most_threatened_town]), GetLocationY(town_loc[most_threatened_town]))
call SetCaptainHome(DEFENSE_CAPTAIN, GetLocationX(home_location), GetLocationY(home_location))
call CaptainGoHome()
```

here no use moveattack 
but more time , the threatened army at town peripheral , like `front_loc` , here and town Distance is 1100 or more
I suspect sys cannot know here is home , so SetCaptainHome or CaptainGoHome will let AI go home_location , Equivalent to leaving the battlefield
This leads to the problem of hesitation and non aggression

**Comment by SMUnlimited** [comment]
AttackMove doesn't trigger the defense captain, it only manages where troops are when **no** attack is in progress, or units which are not currently in the attack group.

**Comment by jzy-chitong56** [comment]
In my impression, I haven't added any units to the defense team, and it seems that amai completely ignored the formation of the defense team

**Comment by jzy-chitong56** [comment]
`exitwhen not town_threatened and not TownThreatened() and not CaptainInCombat(false)`

Is this exit condition intentional
not CaptainInCombat(false)
It seems like when go back in battle and the threat is eliminated
Instead of the end of the battle and the elimination of the threat
But the entire loop doesn't control the attack group, will the attack group really go back to defend？
