### ISSUE TITLE
Where can I  download the map pack that contains a few official maps  with AMAI preinstalled 

### ISSUE THREAD

**Issue by bigcornflake** [SMUnlimited/AMAI#302]
I use MacOs, and cannot install AMAI.
So where can I  download the map pack that contains a few official maps  with AMAI preinstalled ?

Thanks !

**Comment by SMUnlimited** [comment]
https://www.hiveworkshop.com/threads/advanced-melee-ai.62879/page-5

Also you can check comments for full collection of maps created by community.

**Comment by bigcornflake** [comment]
> You can use [Wine](https://en.wikipedia.org/wiki/Wine_(software)) to install AMAI with command line scripts. That's what I've been doing.

Thanks！

**Comment by bigcornflake** [comment]
@atticusmatticus If you just want to get the AMAI map, I can send you some

**Comment by atticusmatticus** [comment]
Thank you, sure that would be great. I'd also still like to know how to install if @ghost sees this.

@bigcornflake where did you find the maps? and where did you put them in your file system?
