### ISSUE TITLE
After using global control for attack and defense upgrades, the desire to upgrade is extremely low

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#304]
`BuildAdvUpgr2`  conditions are too strict and difficult to achieve, coupled with the cancellation of all upgrade codes within the strategy, resulting in slow upgrade of attack and defense

unitper no check 0

try
https://github.com/jzy-chitong56/AMAI/commit/48c56d283f371fbfc5cdd77a167804b903af3a46

**Comment by SMUnlimited** [comment]
Duplicates #412
