### ISSUE TITLE
Still suggest RETREAT_CONTROL check main_army

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#307]
https://github.com/SMUnlimited/AMAI/blob/f388e823b36b342056ceb35719e17de55631324e/Jobs/RETREAT_CONTROL.eai#L118

see the buy job , this job will take one unit go buy some thing
maybe the unit is main hero , so main maybe will go home -- when buy item
now need check main_army

and , maybe main hero die ,  but army not retreat and not use TP , now need check main_army too

and , main hero use TP , maybe army not at within the transmission range ... 
some time , hero just out of treatment or resurrection, the hero selected as the main hero -- maybe not at army within , like just left the base or spring water ， and now the army may still be able to fight , but if hero in the way , he TP not affecting the army

some time , hero being stuck elsewhere and leaving the main army can also distort judgment

Finally, speaking of congestion, this feature has been released and I have tested it well (Need to cooperate with other modifications). However, since you have multiple submissions that have not been reviewed, I will not submit them for now to avoid increasing your workload
https://github.com/jzy-chitong56/AMAI/blob/master/Jobs/FIX_BLOCK.eai

**Comment by SMUnlimited** [comment]
This was an odd condition, removed the major_hero check and only use the CaptainIsHome check.
