### ISSUE TITLE
How to block conversations with in-game computers

### ISSUE THREAD

**Issue by berzerk80** [SMUnlimited/AMAI#31]
First of all, thank you for the new update of amai, and thanks to the application of amai to the use map, we are having fun with our users.
Even if you choose insane mode, Blizzard ai is so stupid, so applying amai is almost essential.
But the only complaint is that I play melee games between people and computers, and the conversations between computers are very annoying.
Is there any way to block computer conversations?
I don't know if there is a way to edit and compile the source myself, but I'm not a developer, so I don't know how.
It would be nice if there was an option to hide the conversations of computers during the game.
I would really appreciate it if you consider it in the next update or release.

**Comment by SMUnlimited** [comment]
Hi Berzerk80,
At the moment it can only be disabled if you compile from source as there is a globalsetting called chatting you can set to false.

**Comment by Ali229** [comment]
This is very redundant especially if there a multiple AI, an option to mute them in the installer would be neat.

**Comment by bgalkows** [comment]
Echoing this -- can we have a feature to mute computers?  In my map with 12+ players, it is constant chatter blocking 1/5th of the screen

**Comment by SMUnlimited** [comment]
Perhaps if it was rate limited to a single message at any one time within say 30 second period rather than fill the screen with all the AI chat messages would that be more reasonable?

**Comment by bgalkows** [comment]
That would definitely work for my use case if a mute option seems ill-suited.  As long as it's a setting players can configure, I think all could appreciate that type of change

**Comment by Ali229** [comment]
> Perhaps if it was rate limited to a single message at any one time within say 30 second period rather than fill the screen with all the AI chat messages would that be more reasonable? 

I think this would work, honestly the only times I want the computer to type is in the start so I know I picked an amai map(hopefully just a single message) and when it's about to quit. The taunt and all when it's 8 computers is just too much.

**Comment by SMUnlimited** [comment]
Rate limit added. Commander can disable chatter from allies.
