### ISSUE TITLE
Have you tried running a new installer on Windows 7 or old windows?

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#317]
It seems to be incompatible with Win7 or old windows, but it is not mentioned in the instructions

**Comment by SMUnlimited** [comment]
True, we are on electron 27, windows 7/8 support was removed in electron 23. 

https://github.com/electron/electron/tree/v27.0.0
> macOS (Catalina and up): Electron provides 64-bit Intel and ARM binaries for macOS. Apple Silicon support was added in Electron 11.
>     Windows (Windows 10 and up): Electron provides ia32 (x86), x64 (amd64), and arm64 binaries for Windows. Windows on ARM support was added in Electron 5.0.8. Support for Windows 7, 8 and 8.1 was [removed in Electron 23, in line with Chromium's Windows deprecation policy](https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice).
>     Linux: The prebuilt binaries of Electron are built on Ubuntu 20.04. They have also been verified to work on:
>         Ubuntu 14.04 and newer
>         Fedora 24 and newer
>         Debian 8 and newer

**Comment by SMUnlimited** [comment]
We should match the current supported stack of war3 so will see if we can move back to 22.

**Comment by jzy-chitong56** [comment]
The lower version of WAR3 can also support XP This is not a good idea

Also, is there any problem with the pull of the installer? I don't think it has been resolved yet
