### ISSUE TITLE
Do you have any plans to continue producing cheat modules?

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#319]
You have previously released a launcher, which was packaged with an EXE using the mpq loading tool. I still use it to release test programs now because the player cost is not high and it is completely temporary, not permanently modified

In fact, for reference Quenching Mod，Today, we can still create cheat modules specifically for remakes, so that some players can directly start cheating when they don't want to install or download map packages

**Comment by jzy-chitong56** [comment]
Even without packaging, just enable local loading and place the script in the directory, supporting versions 1.30.0 and above

**Comment by SMUnlimited** [comment]
I haven't tried it but yes in theory local loading in reforged versions or something like the "WC3 Mod Manager" https://www.hiveworkshop.com/threads/wc3-mod-manager-v1-1-1.308948/ may work so all maps just run with AMAI. I'm not directly including such a tool especially as the old tools often trigger anti virus systems but if we get working instructions can add to readme.

**Comment by jzy-chitong56** [comment]
[AllowLocalFiles.zip](https://github.com/user-attachments/files/15536716/AllowLocalFiles.zip)

Run this registry to enable loading local resources
Create a `Scripts` folder locally and place it in the AI and J script, then run the game

1.30.0~1.31.x : Create in the game `root` directory
1.32.0 + : Create in the game `_retail_` directory

**Comment by jzy-chitong56** [comment]
No additional tools or software required

![image](https://github.com/SMUnlimited/AMAI/assets/48715223/5a270b2b-feab-4af3-9875-122dc21e02a1)

**Comment by jzy-chitong56** [comment]
[Chronicles of the Second War: Tides of Darkness](https://www.hiveworkshop.com/threads/chronicles-of-the-second-war-tides-of-darkness.327574/)
Used a large amount of local resources
Therefore, MAX and LINUX can refer to the way they enable local resources

**Comment by SMUnlimited** [comment]
Added to readme
