### ISSUE TITLE
Inconsistency with AMAI

### ISSUE THREAD

**Issue by Mizo1994** [SMUnlimited/AMAI#32]
After downloading AMAI up to the most recent one, 3.0 using AMAI.exe to install the scripts on maps, the game does not always load AMAI.

There is a huge inconsistency. Sometimes the game would just have the normal AI playing even when playing on the appropriate map. You would then have to restart the match several times and use cheats to reveal the map to see what AI you are fighting against. Only about 20% of the time, you would get an AMAI AI profile to load up in game.

This also applies in team games. 2/6 AIs would only be using AMAI scripts while the rest would be using the standard AI scripts.

Is there a way to just outright delete the standard AI skirmish scripts? I want to only fight against AMAI.

**Comment by SMUnlimited** [comment]
Hi Mizo,

I don't recommend using the old AMAI.exe, it cannot install AMAI correctly with the latest versions of warcraft 3 and has been hidden in 3.0.1. Where it might still work is if you have maps from a really old version of warcraft.

Instead use the new instructions of `InstallTFTToMap.bat "C:\mymap.w3m"`
