### ISSUE TITLE
Why wasn't BJ initially stored in folders

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#322]
I understand that the internet used to be poor, reducing files can shorten download time. But now it's completely unnecessary
Put all BJs into the corresponding version, eliminating version naming, which seems more convenient for installation

![image](https://github.com/SMUnlimited/AMAI/assets/48715223/3a4182f2-0d65-4c77-bdbd-74083aa67602)

**Comment by SMUnlimited** [comment]
It used to be because we copied entire contents of the folder containing the ai scripts to the map mainly to support custom races, and as the blizzard.j is an optional file we would not want to auto include. 

But we now add to map via the *.ai filter so it may now be fine to combine and it won't break anything.

**Comment by jzy-chitong56** [comment]
You can also include VSai for further refinement, including the installer and mode selection

**Comment by jzy-chitong56** [comment]
try to support writing to the registry to achieve sideloading startup ， like this

![image](https://github.com/SMUnlimited/AMAI/assets/48715223/8b69aa4b-cc6f-480e-9b0d-829524cec62c)

**Comment by jzy-chitong56** [comment]
BJ has a default language, and for ordinary players, they do not have the ability to modify files to set the default language. Therefore, for non English players, when using the official version - which is your version - they can only choose the language every time they enter the game. 

If the BJ default language can be set on the installer, they can avoid the trouble of choosing the language every time

**Comment by jzy-chitong56** [comment]
Creating VS AI replicas will be a big project
All installation scripts (InstallToDir. pl) need to be refactored, and I am at a loss and hesitant

The simplest way is to create an installation script for VS AI mode
But there are already too many compiled and installed scripts, which are very unfriendly. The new installer is also too large in size, making it too cumbersome to download  @paulo101977

**Comment by paulo101977** [comment]
> Creating VS AI replicas will be a big project All installation scripts (InstallToDir. pl) need to be refactored, and I am at a loss and hesitant
> 
> The simplest way is to create an installation script for VS AI mode But there are already too many compiled and installed scripts, which are very unfriendly. The new installer is also too large in size, making it too cumbersome to download @paulo101977

And the installer also uses the current scripts. It's just a way to make it easier for laypeople who don't know how to use such scripts.

An alternative would be to modify the installer in such a way as to perform such procedures using commands from the operating system itself. I also don't know if it's viable or complex.

**Comment by jzy-chitong56** [comment]
> > Creating VS AI replicas will be a big project All installation scripts (InstallToDir. pl) need to be refactored, and I am at a loss and hesitant
> > The simplest way is to create an installation script for VS AI mode But there are already too many compiled and installed scripts, which are very unfriendly. The new installer is also too large in size, making it too cumbersome to download @paulo101977
> 
> And the installer also uses the current scripts. It's just a way to make it easier for laypeople who don't know how to use such scripts.
> 
> An alternative would be to modify the installer in such a way as to perform such procedures using commands from the operating system itself. I also don't know if it's viable or complex.

Actually, I just miss the size of the old installer, which was only a few `M` and easy to spread

**Comment by paulo101977** [comment]
> > > Creating VS AI replicas will be a big project All installation scripts (InstallToDir. pl) need to be refactored, and I am at a loss and hesitant
> > > The simplest way is to create an installation script for VS AI mode But there are already too many compiled and installed scripts, which are very unfriendly. The new installer is also too large in size, making it too cumbersome to download @paulo101977
> > 
> > 
> > And the installer also uses the current scripts. It's just a way to make it easier for laypeople who don't know how to use such scripts.
> > An alternative would be to modify the installer in such a way as to perform such procedures using commands from the operating system itself. I also don't know if it's viable or complex.
> 
> Actually, I just miss the size of the old installer, which was only a few `M` and easy to spread

But the size of this current installer can be reduced to the extreme. This is done in the build process. If you optimize this process, the size of the installer decreases.

**Comment by jzy-chitong56** [comment]
@SMUnlimited  can you try

> > > > Creating VS AI replicas will be a big project All installation scripts (InstallToDir. pl) need to be refactored, and I am at a loss and hesitant
> > > > The simplest way is to create an installation script for VS AI mode But there are already too many compiled and installed scripts, which are very unfriendly. The new installer is also too large in size, making it too cumbersome to download @paulo101977
> > > 
> > > 
> > > And the installer also uses the current scripts. It's just a way to make it easier for laypeople who don't know how to use such scripts.
> > > An alternative would be to modify the installer in such a way as to perform such procedures using commands from the operating system itself. I also don't know if it's viable or complex.
> > 
> > 
> > Actually, I just miss the size of the old installer, which was only a few `M` and easy to spread
> 
> But the size of this current installer can be reduced to the extreme. This is done in the build process. If you optimize this process, the size of the installer decreases.

Could you please handle it? Thank you

**Comment by paulo101977** [comment]
> @SMUnlimited can you try
> 
> > > > > Creating VS AI replicas will be a big project All installation scripts (InstallToDir. pl) need to be refactored, and I am at a loss and hesitant
> > > > > The simplest way is to create an installation script for VS AI mode But there are already too many compiled and installed scripts, which are very unfriendly. The new installer is also too large in size, making it too cumbersome to download @paulo101977
> > > > 
> > > > 
> > > > And the installer also uses the current scripts. It's just a way to make it easier for laypeople who don't know how to use such scripts.
> > > > An alternative would be to modify the installer in such a way as to perform such procedures using commands from the operating system itself. I also don't know if it's viable or complex.
> > > 
> > > 
> > > Actually, I just miss the size of the old installer, which was only a few `M` and easy to spread
> > 
> > 
> > But the size of this current installer can be reduced to the extreme. This is done in the build process. If you optimize this process, the size of the installer decreases.
> 
> Could you please handle it? Thank you

I will try to find time, but I can't promise as I am involved in two postgraduate courses and studying artificial intelligence heavily here.

**Comment by jzy-chitong56** [comment]
In fact, it can be more convenient. If players use custom AI, we should be able to automatically help them complete file name modifications and write them
