### ISSUE TITLE
Do not recommend the mod tool you mentioned

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#324]
I used the tool, which was good at the beginning in the lower version. However, when I pointed the tool to 1.36, two issues arose

When using the classic TFT script,  cannot see any maps, yes, you do not recommend using it this way

so I thought it was a script exception and wanted to use a lower version to check if it could run. In this case, no matter how I set it up, reset the registry, restart the computer, delete the mod configuration file, etc., mod only run ROC and cannot run TFT

I wanted to determine the settings for running different EXE files, but unfortunately, I don't know how to compile that source code

**Comment by SMUnlimited** [comment]
Yeah your not supposed to use that tool for 1.36, although comments suggest people have got it to help i didn't include that.
