### ISSUE TITLE
SleepUntilTownDefended Still need to send defensive ally orders

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#329]
SleepUntilTownDefended Still need to send defensive ally orders
Currently, there are only instructions to go home within the loop, but the official ally defense has been disabled, resulting in AI usually not helping allies defend

_Before entering the loop, determine whether the person being threatened is oneself（Player(town_owner[most_threatened_town]) == ai_player）. If not, activate the official defense mechanism and do not send any attack group instructions. After leaving the loop, close it_

**Comment by SMUnlimited** [comment]
Not required the army control job is now the only place to set the home defense location to the appropriate location.
