### ISSUE TITLE
Help with map...

### ISSUE THREAD

**Issue by CGminded** [SMUnlimited/AMAI#33]
I made a map for myself some time ago, it turned out to be very fun, but I was only able to get AMAI2.54PE version of this software working. Trust me, I tried my best, but AMAI2.6.0 just didn't work on my computer, so I couldn't configure the AI to work better...

The map is inspired by WTII's tower island strategy (https://www.youtube.com/watch?v=9QsiyepDN8U)

If someone wants to, they can configure the AI to work better for the map to make it more challenging and release it on hiveworkshop **as their own**. I only have wc3 1.29v, so I can't make it work for reforged properly...
 
 Things that are needed to finish the map properly:
 - Configure AMAI of enemies to prioritize effective strategy to combat tower island strategy
 - Configure AMAI of Player 1 (Red) to never quit game and to never leave the tower island
 - Configure map settings to use newer path (+1.32)
 - Balance tweaks if needed.
 
 I would be very happy if someone could take care of this map as otherwise I don't this it will ever be released...
 
 Download link - https://drive.google.com/file/d/1OVBJYQ6aMhX9qcW40L0Cr506QyZL3x-P/view?usp=sharing

Sorry for posting this on here, I just don't know where else it would be appropriate...

**Comment by SMUnlimited** [comment]
One thing to note 2.6.0 had a bug which means it didn't work with wc31.29. You would need to download 2.6.1 for it to be able to work.

**Comment by CGminded** [comment]
@SMUnlimited I think my problem was I couldn't get it to display the menu with the options at all, even thou I downloaded all the required software...
