### ISSUE TITLE
DEVTOOL BAT /B not working correctly

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#335]
**exit /b %RESULTMAKEVER%** 

I found that the meaning of/B is not to close the window
But in reality, it seems that this did not execute successfully

MakeAll.bat have pause ， but other bat not have , so when use other bat , if err, the window will close , can not see log

That's the problem（If you also think this is a problem）, so I suggest you add pauses to each BAT and refer to my branch

**Comment by Slayer95** [comment]
``exit /b`` correctly allows the ``cmd.exe`` window in which AMAI scripts are called to remain opened after AMAI builds. The apparent malfunction of ``/b`` flag is because, as far as I understand, you run the ``.bat`` scripts by double-clicking, which isn't optimal.
