### ISSUE TITLE
BJ console and cancels training potential problem - ESC

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#337]
We know that ESC cancels training
At the same time, it also triggers the console

It seems that the lower version of the native interface can only recognize one button, ESC

Under normal circumstances, canceling once or twice is not a problem

But in `shared mode`, players may operate extensively through the console
If players often inadvertently select allied buildings and press the console, constantly canceling them will have a profound impact on the battle situation

**Comment by SMUnlimited** [comment]
We need alternate buttons we could use instead of ESC, F7?

**Comment by jzy-chitong56** [comment]
In fact, there is no way to replace it. As I said, the low-level native API does not support monitoring other keys on the keyboard, and it is not good to require players to use chat input
My suggestion is to give a prompt after selecting this mode
