### ISSUE TITLE
Test found a crash

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#342]
(24)Emersion v3.0 Standard Melee.w3x

Random crashes, No error message and no error logs left
It seems that this situation exists on large maps, using 4V4V4V4V3

On my branch. It seems that the crash is related to the JOB thread, and after disabling it, the crash seems to disappear
It seems that this can prevent the collapse  `TQAddJobEx `  >> `//call GetTQLock()`

It is speculated that ADDJOB is used between different threads, but TQ threads ‘ `tq_time` are interval too long, resulting in the fact that `TQRemoveRoot  >> ReleaseTQLock` has not been running (suspected that the path thread reduced the number of jobs after taking on periodic jobs), so they are all trapped in the Get Get QLock loop. 
Why does `TQAddJobEx` enter `GetQLock`? It doesn't seem necessary
      
`call TQAddUnit2Job(2 * sleep_multiplier, BUILD_EXPANSION, 0, expansion_peon, current_expansion)`  Running too much?

-----------------------------------------------
and
TQSleep seems a bit unusual
0 should be fasten so i is 1
`tq_length` has already been used on `TQAddJobEx` so cannot be equal to

```
  function TQSleep takes real time returns nothing
    local integer i = 1
    loop
      exitwhen i > tq_length
      set tq_time[i] = tq_time[i] + time
      set i = i + 1
    endloop
    call Sleep(time)
  endfunction
```

**Comment by SMUnlimited** [comment]
Why does TQAddJobEx enter GetQLock? It doesn't seem necessary
- Multiple threads can modify the job arrays at the same time. To prevent concurrency crashes only 1 thread can modify it at once. Without it at best the arrays get mixed up with inconsistent data, at worst it is a crash.

I do see the issue that if the job thread is large its possible to reach an infinitely calling operation to modify the heap, and without a break it would crash. There is a risk it goes over the total limit allowed.

**Comment by jzy-chitong56** [comment]
It's really strange
I closed many threads and finally realized that it seemed to have caused the crash
Then I don't know where I modified it, it seems to be an expansion gold mine repaired by Duofen Mining, and the collapse disappeared, so it doesn't look like it was caused by JOB

but TQSleep should fix

**Comment by SMUnlimited** [comment]
Try with this commit https://github.com/SMUnlimited/AMAI/commit/03eccfe87ad778a3f6a97b6c5603f56b3ed23c21

**Comment by jzy-chitong56** [comment]
I implanted the code into my branch, but it keeps crashing. I'm not sure if I haven't completely fixed the crash here yet. It's very bad. I ran it a few times last time and didn't crash, but now it's happening again. I want to try removing this modification and checking my branch


_I'll still use the map with 24 people_

**Comment by jzy-chitong56** [comment]
It seems that crash is caused by the floating text of local variables
I have been checking for code
