### ISSUE TITLE
some API only return false

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#343]
```
IssuePointOrder
IssuePointOrderById
IssuePointOrderLoc
UnitUseItemPoint
```
I tested a small portion and found that even if the execution was successful in 1.24e and 1.36.2, the return was still False

This means that the return values of these parameters cannot be directly determined

exception
```
IssueImmediateOrderById 
IssueTargetOrder
IssueTargetOrderById
UnitDropItemPoint
UnitDropItemSlot
UnitDropItemTarget
```

**Comment by SMUnlimited** [comment]
Added log to keep on eye on only one that matters, but even then it will be corrected by next build cycle. So this is more informative nothing really to fix.
