### ISSUE TITLE
AMAI doesn't work in Reforged 1.36.2

### ISSUE THREAD

**Issue by infseeker** [SMUnlimited/AMAI#346]
Windows 10
Reforged 1.36.2
AMAI 3.3.5a

I tried to install it on different official maps extracted with CascView (for example EchoIsles v2), in different ways (via UI, CMD), but the bot (default, not AMAI) just stands on its base and does nothing.

**Comment by infseeker** [comment]
> Download
I don't need trojan file.

**Comment by infseeker** [comment]
I found out that AMAI only works on old maps (from ...\Warcraft III\Maps\Download\ without "S2" in the name). It seems that all maps with "S2" have a different format, so AMAI does not work correctly. For example, it works for (2)EchoIsles.w3x, but does not work for (2)EchoIsles_S2_v2.2.w3x.

**Comment by SMUnlimited** [comment]
The S2 maps appear to be recently new for 1.36.x. Not sure why you can't convert to JASS as should be a standard melee map. I'll have to look into it when i have some time incase they done something different.

**Comment by SMUnlimited** [comment]
Can't reproduce with the same map, convert to LUA, save map, install AMAI, working as expected.
