### ISSUE TITLE
some strategy key build same or 0

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#356]
it is right? maybe 2 need give tier ?
![image](https://github.com/user-attachments/assets/f5b9ca55-43a0-4995-9358-f402da9fabfd)

---------------------------------
maybe no give 0 and human no give tier 1 unit
![image](https://github.com/user-attachments/assets/83ef53ba-9205-491a-8c1d-7ec24facf84b)

**Comment by SMUnlimited** [comment]
Its valid for these to be 0 in the right circumstances. Key buildings increase likelihood of picking strategies if units or buildings are upgrades already done. Having the same key building twice is probably not optimal.
