### ISSUE TITLE
slm_start and slm_end

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#357]
At first, the adjustment was just to reduce lag on crowded maps
Now you seem to have almost fixed the stutter
Perhaps it's time to restore these settings, as delays may affect performance

Many player feedback that the intensity of 3.20+ is lower than that of 3.1.1, and I suspect this may be one of the reasons

```
  set slm_start = 4
  set slm_end = 18
  set slm_start_mult = 1
  set slm_end_mult = 3.2
```

**Comment by SMUnlimited** [comment]
While not sure on reducing to old values entirely, i've tweaked and instead made it as players are defeated the remaining AI's will get more responsive.

**Comment by jzy-chitong56** [comment]
I don't quite understand why only REF was modified. Is the TFT missing

**Comment by jzy-chitong56** [comment]
Perhaps it can be dynamically set based on the number of players
`GetPlayers()`

When there are fewer players, it should be more flexible. The lower limit starts from the old value until the new value, and a random variable is added in the middle. This random variable interval should not be completely random, perhaps it can be linked to some personality parameters of the file

**Comment by SMUnlimited** [comment]
Only needs ai players as its too many script operations within the same frame which can lag or crash the game. Randomness is just to help distribute that load and reduce scripts all running at exactly the same time.
