### ISSUE TITLE
Distortion operation to set hallCount = hallCount + TownCountDone(racial_hall[1])

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#364]
```
      loop
        exitwhen i > tiernum
        set hallCount = hallCount + TownCountDone(racial_hall[1])
        set i = i + 1
      endloop
```

`TownCountDone(racial_hall[1])`  
I believe this already includes three layers, and after the loop, it has expanded by at least three times, which is inaccurate and has caused hallCount to remain at 1
maybe should use `        set hallCount = hallCount + GetUnitCount(old[acial_hall[i]])` 

The final reset is also very strange, not every time it can reach the end, so the reset may not be triggered, resulting in an increasing demand

_The same problem exists in the construction of human towers, and my branch has been fixed_

**Comment by SMUnlimited** [comment]
Good spot fixed to not do the loop, from a mod support point of view this causes non-obvious problems if they don't include the upgrade units in add to counting. But no idea how to solve or warn about that right now for modders as the add to counting is correct place.

**Comment by jzy-chitong56** [comment]
hallCount is 0 , so no need add hallCount ??
