### ISSUE TITLE
Still very strange, there are resources not being used

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#365]
` if SetProduce(afford_qty,old_id[unitid],town) then `
Global interception has been carried out here, cannot triggered  `set neededPeons = 0 // Reset`

![image](https://github.com/user-attachments/assets/7a637b99-dfc2-4cce-8b42-1fd2e61d0445)

**Comment by jzy-chitong56** [comment]
It seems that the people who have problems are all from the human race
How much of this submission should be withdrawn

**Comment by SMUnlimited** [comment]
I'll keep an eye myself, but that could be a bug in a particular strategy somewhere or need the debug logging when it goes wrong on what it couldn't build or got stuck on. 

If neededPeons = 0 isn't being hit then PeonBuilder and various other important build systems are not being triggered potentially hinting at a thread crash or stuck in a loop.

**Comment by jzy-chitong56** [comment]
```
    if SetProduce(afford_qty,old_id[unitid],town) then
      if needed3[unitid] == UPGRADED then
        set available_time[unitid] = ai_time + GetUnitBuildTime(old_id[unitid]) / 5 + 1
      endif
      if (afford_qty + have_qty == need_qty)  then
        return BUILT_ALL
      else
        return BUILT_SOME
      endif
    else
      return CANNOT_BUILD
    endif
    set neededPeons = 0 // Reset
```

It can never trigger
maybe change some code
```
    endif
    return CANNOT_BUILD
    set neededPeons = 0 // Reset
```

**Comment by SMUnlimited** [comment]
Its reset as part of OneBuildLoopAM()
```
function BuildLoopAM takes nothing returns nothing
  local integer blc = 0
  local integer timing = 0
  call OneBuildLoopAM()
  call StaggerSleep(1,5)
  loop
    //call Trace("Build Loop")
    set timing = ai_time
    set blc = blc + 1
    call OneBuildLoopAM() // Reset happens here
```

If this isn't called every 5-15 seconds their is a critical bug in the build code.

**Comment by jzy-chitong56** [comment]
It looks like the anomaly has disappeared


```
function OneBuildLoopAM takes nothing returns nothing
....
set neededPeons = 0 // Reset
endfunction
```
