### ISSUE TITLE
Chinese translation errors, missing and outdated

### ISSUE THREAD

**Issue by Pixyy** [SMUnlimited/AMAI#37]
Thanks to @keamspring for fixing the Chinese language translation/encoding issues, the language for Chinese is available again.
But during the test, I found some other problems with the Chinese translation. Some translation is confusing while others are missing in some sentence. This is a problem I didn't meet in AMAI 2.54b version. So I checked the Language folder and found out where the problem is.
There are two versions of the Chinese translation in AMAI 2.54. Dr.Fan's version was correct but it used ANSI standard, which could make it unavailable in the game. Sheeryiro's version used UTF-8 with BOM. Therefore, the former is deprecated, while the latter has been retained until later versions.
But Sheeryiro's version has a lot of serious mistakes, such as confusing words Dryad and Druid as well as Banshee and Sorceress. So many translations are completely wrong which might mislead players who fight alongside AMAI or use commander.
And in its Strategy.txt there are lots of lines missing, so the translation of the strategy sentences is mixed in Chinese and English. 
The sentences in ChatTaunt.txt and other Chat.txt were written in 2004. Many words and sentences are totally out-of-date. I bet the new generation can't even read these sentences fluently, let alone understand them.

And there are some new issues in AMAI 3.01's translation. In AMAI 2.54, AI's strategy chatting and the sentence in Strategy.txt are the same. But in AMAI 3.01, there are more words at the end of the sentence. Those words are about the enemy units AI wants to counter with, such as heavy armor, piercing. 
![translate error_1](https://user-images.githubusercontent.com/88197432/127745717-f02a6a05-4e8c-421b-a187-9d9731591b8f.png)

I guess is related to the Dynamic strategies system. I can't find these words in the Languages folder so I can't translate them.

Could you tell me where can I find these words and which file should I put my translation in?

My goal is to check and rewrite the Chinese translation. Make it correct and keep up with the times.
This might takes few days, and when I finish, I will submit it after running the test locally. 
Meantime I will upload some pictures show the change before and after so that you can be assured that it works.

Thanks again for your dedication to this project. There are far more Chinese players using AMAI than you think. People are thinking highly of it, and even some pro players sometimes use AMAI to practice. But lots of them are still using AMAI 2.54 because they don't know this project is still updating. I'm about to write an article that fully introduces the newest AMAI and post on Tieba(Chinese version of Reddit) after the release of a more complete version.

Looking forward to your reply.

**Comment by SMUnlimited** [comment]
Nice to hear its still getting alot of use.

Its not quite so straight forward at the moment, they currently not localized and pulled direct from https://github.com/SMUnlimited/AMAI/blob/master/TFT/Strengths.txt 

and merged with the chat_dynamic_counter text which is localized: https://github.com/SMUnlimited/AMAI/blob/master/Languages/English/ChatMisc.txt

So we need a framework over the top for full language support of strengths.

**Comment by Pixyy** [comment]
Got it. 
I will tackle other Chinese translation issues and make a pull request when it's done. If you successfully localize the strengths.txt, I will do this part of the translation too.
