### ISSUE TITLE
build two town at home, GetUnitCountAlt need check

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#373]
it seems except UD

![image](https://github.com/user-attachments/assets/b06baf66-41be-4543-a8be-c945029de5a3)

**Comment by SMUnlimited** [comment]
I've just seen undead also do it

**Comment by SMUnlimited** [comment]
Caused by tier 3 buildings. It checks for tier 2 and correctly ignores the teir3 upgrade, but then that needs a tier 1 and that will add the tier 3 into the count and only ignore tier 2.

**Comment by jzy-chitong56** [comment]
Technology is research at once, and sending research commands repeatedly seems insignificant

but some tower have can upgrade, will the same problem occur
I noticed that there seem to be too many towers built by the human race and UD

**Comment by paulo101977** [comment]
> it seems except UD
> 
> ![image](https://private-user-images.githubusercontent.com/48715223/369413062-b06baf66-41be-4543-a8be-c945029de5a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTIwMDcsIm5iZiI6MTcyNzA1MTcwNywicGF0aCI6Ii80ODcxNTIyMy8zNjk0MTMwNjItYjA2YmFmNjYtNDFiZS00NTQzLWE4YmUtYzk0NTAyOWRlNWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDAwMzUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMDIxOWRlOTY5ZTZiZDE0ZTZhNGY5MGUyOWY1NjNiNzgxODg1MzljYjVmNjVhOTFmZWMxYTE4OTdlOWE1Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U1isRCsqzrLwRmuD0UNa7LcxbyvGm-_6k4MtlRj-3uY)

And when they build two towns in the gold mine? Is this also planned?

**Comment by jzy-chitong56** [comment]
> > it seems except UD
> > ![image](https://private-user-images.githubusercontent.com/48715223/369413062-b06baf66-41be-4543-a8be-c945029de5a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTIwMDcsIm5iZiI6MTcyNzA1MTcwNywicGF0aCI6Ii80ODcxNTIyMy8zNjk0MTMwNjItYjA2YmFmNjYtNDFiZS00NTQzLWE4YmUtYzk0NTAyOWRlNWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDAwMzUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMDIxOWRlOTY5ZTZiZDE0ZTZhNGY5MGUyOWY1NjNiNzgxODg1MzljYjVmNjVhOTFmZWMxYTE4OTdlOWE1Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U1isRCsqzrLwRmuD0UNa7LcxbyvGm-_6k4MtlRj-3uY)
> 
> And when they build two towns in the gold mine? Is this also planned?

This is another issue that has been fixed in my branch
