### ISSUE TITLE
（devtool）issues for Optimization compilation and third-party AI

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#381]
I suddenly remembered that : `optimized compilation` not compatibility with third-party AI -- that mean optimized compilation is not applicable to `VS AI` mode

In new installer and installation script, it may be necessary to verify -- `optimized compilation` cannot install `VS AI`
but I will not write this layer of verification code -- _sorry, I really really not know how verification , emmm..._ 
（Perhaps need split it into another folder to store optimization scripts）

Please consider this before merging this [submission ](https://github.com/SMUnlimited/AMAI/pull/374)

Also, I apply for you to consider this compromise solution - `optimizing compilation` by checking if the `script exists first`, and running a normal compilation once `if it does not exist` to ensure that the optimization compilation can proceed normally

**Comment by SMUnlimited** [comment]
Fixed VSAI optimise support in https://github.com/SMUnlimited/AMAI/commit/a41373cc0a49802aa498d36def8848babb63db4b
