### ISSUE TITLE
attacking player is not active ， because active_expansion

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#389]
There is a speculation that during 1v1 or other ffa, 4-player maps are often used, or 2-player maps themselves have a lot of gold mines, which leads to `active_expansion` work and AI continuous entry into `call Trace ("Creep the Expansion")` mode until the number of gold mines reaches 3, making players think that AI does not like to find him

try fix
https://github.com/jzy-chitong56/AMAI/commit/329dd06412e0498c843521aa4c1da34ed7043947

**Comment by SMUnlimited** [comment]
Active expansion rolled up into fast expansion logic.
