### ISSUE TITLE
In-scripts language configurable from installer

### ISSUE THREAD

**Issue by Slayer95** [SMUnlimited/AMAI#390]
~~I think this should be possible by reading ``GetPlayerName(ai)`` on initialization, and comparing to known values for each language.~~

It would set the default language to be used in case the commander is not installed.

**Comment by jzy-chitong56** [comment]
The plan is as follows

the language of the installer can be modified here, as well as the default language of command and COM. I think I can implement the second half (in fact, command installation has already been implemented, and I will update https://github.com/SMUnlimited/AMAI/pull/374 , but you haven't merged yet, is there really something wrong?). 

As for the first half, I am powerless

![image](https://github.com/user-attachments/assets/255b3db8-3919-41e3-bfb6-8f91bc5c8269)

**Comment by Slayer95** [comment]
My idea was so that people from different countries can play together with AMAI, each in their own language. I briefly tried to implement it, but failed. I will probably put more effort into it later.

But in the offchance that my idea cannot be done, setting language from the installer would be an improvement in its own.

**Comment by jzy-chitong56** [comment]
`JS` done , now have not `TS sync code` and `html` , but maybe `bat install` should have same set

```
const filePath = path.join(__dirname, `Scripts\\TFT\\bbb.j`); // 更改为你的文件路径
// 读取文件
fs.readFile(filePath, 'utf8', (err, data) => {
    if (err) {
      process.send(`错错错错错`);
        return;
    }
    // 要搜索的文本和替换后的文本
    const searchFor = 'string language = "eee2"'; // 这里是你想要替换的文本
    const replaceWith = 'string language = "aaa"'; // 这里是你想替换成的新文本
    // 执行替换
    const updatedData = data.replace(new RegExp(searchFor, 'g'), replaceWith);
    // 写入新内容到文件
    fs.writeFile(filePath, updatedData, 'utf8', (err) => {
        if (err) {
          process.send(`写入错错错错错`);;
        } else {
          process.send(`完成11`);;
        }
    });
});
```

**Comment by jzy-chitong56** [comment]
> My idea was so that people from different countries can play together with AMAI, each in their own language. I briefly tried to implement it, but failed. I will probably put more effort into it later.
> 
> But in the offchance that my idea cannot be done, setting language from the installer would be an improvement in its own.

then you need every player show one chat , should use BJ real the player Localized language . This is the most accurate, otherwise it would be difficult to implement solely through scripts, and it would still be difficult to implement maps without a console installed

**Comment by jzy-chitong56** [comment]
backlanguage support compilation
Let's see if it can give you inspiration @Slayer95 

https://github.com/jzy-chitong56/AMAI/commit/ad969b5eb022dbd83f19f45f8e63a5b0f51efe2c

**Comment by Slayer95** [comment]
Well, that's a start. I need to figure out stuff yet.
1. Whether ``GetPlayerName()`` is actually a valid API from AI scripts.
2A. If ``GetPlayerName()`` is indeed valid, then use templates according to my proposal in the original post. Unfortunately, I am still not very familiar with AMAI templates, so thanks for the pointer.
2B. If ``GetPlayerName()`` is not valid, investigate alternatives such as ``GetLocalizedString()``.

Independently from the previous question, it would be great to modify the Commander code to use ``GetLocalPlayer()``, and investigate and guard against possible desynchronizations.

Official branch is looking pretty good, so I'll probably get to it soon. I also need to review Spanish translations after the pro-Lua localization changes.

**Comment by jzy-chitong56** [comment]
`GetLocalizedString` It cannot run in the script and must rely on triggers from the commander module to load. I suggest you abandon this way of thinking

You can register all languages at the same time and let players choose for themselves, of course, this also requires the Commander module Afterwards, having the AI send different languages according to different choices during transmission is very cumbersome, and I even suspect that it will affect game performance

You can't make a unique judgment based on a name. As I mentioned before, I can use a full English name, but in reality, I can't understand English at all. If you judge based on a name, will you assign it to me in English?

**Comment by Slayer95** [comment]
> You can't make a unique judgment based on a name. As I mentioned before, I can use a full English name, but in reality, I can't understand English at all. If you judge based on a name, will you assign it to me in English?

Presumably, your WC3 computers are named something like <span class="notranslate">电脑（疯狂）</span>, as opposed to <span class="notranslate">Computer (Insane)</span>, or whatever. That's what I am aiming to check for.

**Comment by jzy-chitong56** [comment]
This is quite awkward. Simplified Chinese has undergone two translations and there are some strange versions that vary in different versions

If you want to use this logic, just judge the local language directly. I should have a reference for it
Find a button that is available in all versions to determine, such as `exiting the game` or `start the game`

https://www.hiveworkshop.com/threads/detect-game-version-getpatchlevel.308204/post-3577816

![Uploading 420b5a6fb2f8f8bcf899391fc74bf4b6.png…]()

**Comment by Slayer95** [comment]
``GetPlayerName()`` doesn't fully work from AI scripts, and there's a too large desync risk because of the different amounts of string handles that each different localization creates. The benefit is very small, too, so the gains will not outweigh the losses.

Closing.

**Comment by Slayer95** [comment]
Actually, I think @jzy-chitong56 volunteered to make language configurable from the installer?

**Comment by jzy-chitong56** [comment]
try this , if you can    @Slayer95 

https://github.com/jzy-chitong56/Electron/actions/runs/11675549532

**Comment by Slayer95** [comment]
Tried it, @jzy-chitong56 . So, I think you intended to make the scripts language match the installer language? That's fair enough. However.

```
args-install-message #### AMAI set Scripts Languages ####
main.246d49d50974a4f5.js:1 args-install-message lang string language = "Spanish"
main.246d49d50974a4f5.js:1 args-install-message #### Installing AMAI for TFT ####
```

Yet, ``common.ai`` says:

```
	boolean campaign_ai = false

    string language = "English"
    
    string ai_id = ""
```

**Comment by Slayer95** [comment]
[ba046001caa59362fc0711db75112e912206e6a6](https://github.com/jzy-chitong56/Electron/commit/ba046001caa59362fc0711db75112e912206e6a6#diff-b76e31c20a048d49a8ea0ada78521752275c44d8a5e0d1e9d69fb6756ac1b2d8R91)

At least one of the problems is that you are using ``fs.readFile`` and ``fs.writeFile`` (async, i.e. parallel versions), instead of ``fs.readFileSync`` and ``fs.writeFileSync`` (synchronous, blocking).

https://nodejs.org/api/fs.html#fsreadfilesyncpath-options

**Comment by jzy-chitong56** [comment]
I haven't been 100% successful either. As for the code, it all depends on AI, and the AI level in our country is indeed relatively low. In addition, foreign AI generally requires agents to use Take a look when you have time

**Comment by SMUnlimited** [comment]
Thanks, pulled in what you had and ensured it can be turned on and off.
