### ISSUE TITLE
ChooseAnEnemyTarget seems to have caused return false impression , in the early stages of the game

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#394]
When acquiring enemy targets, especially at 1V1, `IsTargetGood` always returns false
This resulted in continuously entering CREEP attack mode
Usually, `IsTargetGood` will return true when the AI food reaches 70 or higher
This will make players think that AI will not attack if its food is always less than 80 --- At least on my branch

_If the development is affected and the food cannot break through, the impact may be even greater_

-----------------------------------------------------------------------------

Also, I remember you said before that attacking strategy will never be set to 4, and it doesn't look like it will be set to 1 or 3 now. This means that some judgments here will never be triggered, so I want to confirm if there is a mistake here, because writing this will only retrieve extensions
```
ChooseAnEnemyTarget
  .........
   set g = SelectByLocation(g, enemy_base, 1000, false)

```

**Comment by SMUnlimited** [comment]
Looks fine for 1v1 as its based on uncertainity and profile aggressiveness?

Actually there is an issue i can see with allies as it adding enemy ally strength into the mix but doesn't include allys in own strength so in large games this would always return false.

Attacking strategy is just set to the optimal right now. The others are not currently in use except the FFA mode, but there used to be something in the commander to change it.

**Comment by jzy-chitong56** [comment]
The problem is that they believe 3.3.4 will be more aggressive in the initial stage

**Comment by SMUnlimited** [comment]
Profile settings need to be tweaked if still a problem, but otherwise is functionality correct.

**Comment by jzy-chitong56** [comment]
There is no problem with the personal profile, and this change is not appropriate. I apologize, but I think it would be better to look for the problem during training. I suggest you use VS AI for comparative testing to see the difference in FOOD between the two sides at the same time
Also, I was wondering if it's possible to restore this change, as it's really unnecessary

**Comment by jzy-chitong56** [comment]
Because the feedback is from `1 V 1` or `1 V multi bit AI`
I suggestion consider the enemy's allies
