### ISSUE TITLE
SleepInCombatAM like have bug

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#398]
`set u` is  `if (lastcaptainx != 0 and lastcaptainy != 0) then`
In fact, this condition is almost 100% met, which means that it will be reset every time the loop is repeated. I think we need to add self-locking here and only reacquire when `U` is `null` or dead

`if (lastcaptainx != 0 and lastcaptainy != 0) and (u == null or not UnitAlive(u)) then`

--------------------------------------------------------------------------------

`call TeleportCaptain(lastcaptainx, lastcaptainy)` maybe need check Combat
```
if not CaptainInCombat(true) then
  call TeleportCaptain(lastcaptainx, lastcaptainy)
endif
```

--------------------------------------------------------------------------------

`if (u != null and (not CaptainInCombat(true) or CaptainRetreating() or CaptainIsHome())) then`
It seems that the parentheses are written in the wrong position here. Is the original intention
```
not CaptainInCombat(true)
not CaptainRetreating() 
not CaptainIsHome()
```

**Comment by jzy-chitong56** [comment]
TeleportCaptain maybe need check Retreating
```
        if not CaptainInCombat(true) and not CaptainRetreating() then
          call TeleportCaptain(lastcaptainx, lastcaptainy)
        endif
```

**Comment by SMUnlimited** [comment]
No unless true retreat control is engaged its fine in this case as it should stay around by design.
