### ISSUE TITLE
(The recovery ability of the orcs is obviously insufficient, resulting in small waves sent to fights) 兽族恢复能力明显不足，消耗起来续航很差

### ISSUE THREAD

**Issue by Arondight** [SMUnlimited/AMAI#399]
中期开始明显家里趴窝一堆残血的，然后一小波出去打架，导致这个种族打起来很弱势，请改改逻辑，至少让 ai 表现的像正常玩家

**Comment by SMUnlimited** [comment]
Duplicates #331

**Comment by wsh3166Sir** [comment]
I modified the map to add Life Spring effect to bases, fixing the problem partially :D @Arondight
