### ISSUE TITLE
GetIntervalCreep is it possible to fall into dead loop ?

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#403]
`return GetIntervalCreep(u, lower, upper, str, anti_air_strength, false, sd)`
here sd not `-1`
but other have 
`return GetIntervalCreep(u, lower, middle, str, anti_air_strength, allow_air, sd - 1)`

**Comment by SMUnlimited** [comment]
Yes I think there is a possibility for this to get stuck in infinite loop, applied fix.
