### ISSUE TITLE
Can you verify this picture？

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#404]
https://www.hiveworkshop.com/threads/warcraft-3-re-launched.356363/#post-3641776

It is true that migrating to the interstellar engine can integrate with large-scale AI models, but I have no understanding of this aspect.............

**Comment by SMUnlimited** [comment]
Speculation/hope, I wouldn't put much stock in such things until we see otherwise.

Yes the starcraft 2 engine does make it easier to hook with modern AI tech, for example see https://github.com/google-deepmind/pysc2?tab=readme-ov-file  and https://github.com/Blizzard/s2client-proto
