### ISSUE TITLE
(devtool)  system "MPQEditor a \"$dirname/$filename\" Scripts\\$ver\\*.ai Scripts"; Not very friendly

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#409]
The reason why I separated the official AI into folders is to avoid writing all the scripts at once. Although the official scripts are not large, when there are many map files, these volumes will accumulate and not be conducive to the spread of compressed files
When VS AI is not used, these scripts are redundant

**Comment by SMUnlimited** [comment]
They need to be a copy for optimise support so can't just copy last minute from vanillaAI, and the original source code folders are not the natural release artifacts. Should be just the script folder.
