### ISSUE TITLE
finish_strategy_change Is it possible to cause a dead loop?

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#414]
` rp_strat` There may be negative numbers present？？？？
`strategy_roll` Always greater than 0

`if strategy_roll <= sum then`  Negative numbers will never be greater than 0

and i should check max STRAT  -- `rp_strat_length
`
```
  loop
    set sum = sum + rp_strat[rp_strat_sort[i]]
    if strategy_roll <= sum then
      //if rp_strat[rp_strat_sort[i]] / Max(rp_strat[strategy], 1) > strategy_change_threshold then
      set strategy = rp_strat_sort[i]
      set chosen_strategy = strategy
      call SetChatVar("Strategy", GetCurrentStrategyName())
      //endif
      return
    endif
    set i = i + 1
  endloop
```

**Comment by SMUnlimited** [comment]
Anything 0 or less is ignored. make_rp_strat_positive makes everything 0, and then 0 priority can never be picked as a strategy.
