### ISSUE TITLE
ORC basic data does not match

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#415]
The official script is missing a letter
_By the way, 2.0 did not modify the API_

![image](https://github.com/user-attachments/assets/7ff05174-f3ca-4dd5-8b1a-4e936de28280)

**Comment by SMUnlimited** [comment]
Both ENDURANCE and ENDURANE are in the ability list. Not ideal but has to support both incase they ever update the vanilla AI as then its a straight copy in update.
