### ISSUE TITLE
Optimised AI scripts , What is it  ?

### ISSUE THREAD

**Issue by YouMoMCallME** [SMUnlimited/AMAI#434]
(Installer) New option that defaults to true which will install the optimised AI scripts.
What is the difference between Optimised AI and normal AI (when we turn off this option in the Launcher) ?

P.S Thanks for the new version of the AI I was really looking forward to it :)

**Comment by SMUnlimited** [comment]
Just uses a little less CPU and less memory that is all. If your system struggles it can be useful.

**Comment by Kingytrewq** [comment]
Hello, after checking the optimization script, I experienced a crash while playing a 6V6 game, and I no longer checked this option. Currently, I am still testing it
