### ISSUE TITLE
Undead tried to buy 2 heroes at same time

### ISSUE THREAD

**Issue by SMUnlimited** [SMUnlimited/AMAI#439]
It trained a death knight and tried to buy a neutral hero before it went to tier 2. Was 24 players so maybe due to the delayed operations it somehow caused this to occur.

Was using necro strategy.

**Comment by jzy-chitong56** [comment]
One logic is that it triggered the reacquisition of heroes, but buy hero job was not monitored

**Comment by jzy-chitong56** [comment]
One logic is that it triggered the reacquisition of heroes, but buy hero job was not monitored


try
https://github.com/jzy-chitong56/AMAI-CN/commit/e7a962a3bdb9d943f64d7b6032cf23f402fdbd02

**Comment by SMUnlimited** [comment]
Thanks and found some other issues with recalculation which i've resolved.
