### ISSUE TITLE
The big map 6V6 still crashes without any error reports

### ISSUE THREAD

**Issue by Kingytrewq** [SMUnlimited/AMAI#442]
Hello, greetings. Your AI is very fun, but after installing the latest version 3.4.0 and playing the 6V6 map, I checked the optimization script and encountered an error free crash. Is this related to checking the optimization script before installation? Thank you for your attention

**Comment by SMUnlimited** [comment]
Still outstanding issues on this, but will be unrelated to optimization. Optimization would help with any resource contention related crashes though. 

See #386

**Comment by Kingytrewq** [comment]
Okay, thank you. I understand, but will you fix the crash in the future? It's still related to the game's engine, not Amai

**Comment by Kingytrewq** [comment]
Thanks



---- Replied Message ----
| From | ***@***.***> |
| Date | 11/22/2024 20:17 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [SMUnlimited/AMAI] The big map 6V6 still crashes without any error reports (Issue #442) |

Still outstanding issues on this, but will be unrelated to optimization. Optimization would help with any resource contention related crashes though.

See #386
