### ISSUE TITLE
Abnormal mining behavior in certain maps

### ISSUE THREAD

**Issue by Ocatopuss** [SMUnlimited/AMAI#443]
There is a chance that Human and Orc will mine farther away if there are other gold mines in the vicinity (ignore the starting one), and will stop mining if the target mine is occupied and will not mine from the nearest/starting one.
Night Elf and Undead also have a chance of not mining, but that seems to have been fixed or at least mitigated in recent releases.

Here are some map samples:

[Map samples.zip](https://github.com/user-attachments/files/17872089/Map.samples.zip)

These were found on 11.6 and can be confirmed still exist in f30da4a.
jzy-chitong56's fork seems mining normally.

**Comment by SMUnlimited** [comment]
Duplicates #323

**Comment by Ocatopuss** [comment]
The fix seems to be working. Thanks for your and jzy-chitong56's time and talent.
