### ISSUE TITLE
Harass is triggering units into a permanently frozen state

### ISSUE THREAD

**Issue by SMUnlimited** [SMUnlimited/AMAI#444]
Not actually affecting 3.4.0 much as harass was slightly broken.

**Comment by jzy-chitong56** [comment]
To fix this issue, I `tag` all `RemoveGuardPosition` to find out where it was caused - freezing. 
If you encounter the same phenomenon, when you see a frozen unit, exit the game, replay it, stare at the unit, and see what the logs say

**Comment by SMUnlimited** [comment]
I have a vein of thought, when the strategies are changed or potentially changed it resets the hashtable resulting in it just forgetting everything if a harass is still running.

**Comment by SMUnlimited** [comment]
Harass no longer freezing units, but harassments still not happening

**Comment by jzy-chitong56** [comment]
Aha, this is quite awkward. I believe you have removed the removal Alert point, which is the culprit of the freeze. 
Why don't try adding it back

**Comment by jzy-chitong56** [comment]
```
    if state_attacking then
      call GroupEnumUnitsInRange(g,GetUnitX(hu),GetUnitY(hu),harass_radius_attack_ranged,null)
    else
      call GroupEnumUnitsInRange(g,GetUnitX(hu),GetUnitY(hu),harass_radius_flee_ranged,null)
```

At the beginning of the harassment, the unit of the harassment group was far away from the target and had not yet been `RemoveGuardPosition`
So when we were forming the harassment group before, we had to remove it in order to trigger it
