### ISSUE TITLE
RB's calculations will be repeated

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#445]
https://github.com/SMUnlimited/AMAI/blob/5a54e1ffb86c0ec85779f28448bfe25ca48a83db/common.eai#L5988

The same campsite will be counted multiple times, and the reason why I judge the distance is to avoid this, because later on, we still need to rely on the path unit to move to the position where the unit is obtained. With more units, the possibility of path units crowding each other on the road will increase（I'm not sure how to accurately express this meaning）, indirectly increasing time. Time is very precious in the early stages of the game

_This calculation is redundant and wasteful of performance, but of course, the strength calculation results are not biased_

**Comment by SMUnlimited** [comment]
I'm aware, but had to make sure it was behaving the right way, as you only avoided that with the first unit, it didn't work for all the creeps and was still picking orange creeps.
