### ISSUE TITLE
TeleportCaptain maybe override AttackMoveKill

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#447]
Do need prevent it `TeleportCaptain` override `AttackMoveKill` ??
and not send `TeleportCaptain` when Combat

change all like
```
      if CaptainInCombat(true) then
        call AttackMoveKill(target)
      elseif c_ally_total > 0 and not ally_override then
        call TeleportCaptain(GetUnitX(target), GetUnitY(target)) // Override hardcoded logic from attackmovekill which will help allies
      endif
```

**Comment by SMUnlimited** [comment]
TeleportCaptain is being used to override attackmovekill target so yes that is intentional. In team games the attackmovekill command is often ignored based on hardcoded logic. But teleport captain forces us to target the right location and ignore the team target. 

I haven't seen any problems with how it is currently in games, have you seen otherwise?

**Comment by jzy-chitong56** [comment]
The main concern is that `TeleportCaptain` will send `move` commands, overwrite `attack`, and stop the unit's attacks. 
Normal attacks should not be interrupted, as this will weaken the battle

**Comment by SMUnlimited** [comment]
I''m going to revert this or at least leave disabled as its it is just dancing between the two locations, while at least before it prefers one or the other. I think i need to create our own attackmove system for combat to avoid using the hardcoded function.

**Comment by jzy-chitong56** [comment]
`if true or`
here why is true ??  if need  `elseif` always can not run , just del this code


```
        if true or CaptainAtGoal() or (attack_length_counter == 0 and not CaptainInCombat(true)) or CaptainInCombat(true) or ally_override or c_ally_total == 0 then
          call AttackMoveKill(u) // Use existing troops
        elseif (c_ally_total > 0 and not ally_override) then
          call CaptainAttack(GetUnitX(u), GetUnitY(u)) // Override hardcoded logic with attackmovekill as ally targets will change the attackmovekill we wanted. Teleport ignores the ally control.
        endif  
```

**Comment by jzy-chitong56** [comment]
`if true or`
here why is true ??  if need  `elseif` always can not run , just del this code


```
        if true or CaptainAtGoal() or (attack_length_counter == 0 and not CaptainInCombat(true)) or CaptainInCombat(true) or ally_override or c_ally_total == 0 then
          call AttackMoveKill(u) // Use existing troops
        elseif (c_ally_total > 0 and not ally_override) then
          call CaptainAttack(GetUnitX(u), GetUnitY(u)) // Override hardcoded logic with attackmovekill as ally targets will change the attackmovekill we wanted. Teleport ignores the ally control.
        endif  
```

**Comment by SMUnlimited** [comment]
I've disabled as it needs more work.

Ultimately needs to still do an attack move without going to help the allies. As all the alternative attack functions that don't attack the team target are not running an attack move.

**Comment by SMUnlimited** [comment]
Duplicates #467
