### ISSUE TITLE
SleepUntilTownDefended no need send call CaptainGoHome()

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#456]
`    call CaptainGoHome() // town threat check will already set this to correct place to defend`

town threat check will already set this to correct place to defend  -- yes , but `CaptainGoHome` maybe It's going home -- `home_location` ，  so if threatened town not `home_location` -- Isn't there a conflict here?

**Comment by SMUnlimited** [comment]
CaptainGoHome will go to the whichever home location has been set. 

The only issue i have with the town defense is units don't actively move to where they needed once they are at home. They just sort of float around or wander around the map or infinitely fight. This is where actually making town defense an attack will resolve this as it will form the army and force units to defend locations.

**Comment by jzy-chitong56** [comment]
Actually, only a `defense group  -- DEFENSE_CAPTAIN` was set up in town threat check. Are you sure you don't need to set up an `attack group  -- ATTACK_CAPTAIN`  `BOTH_CAPTAINS`??
