### ISSUE TITLE
SetTierBlock ...  Too idealistic

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#457]
Need to consider battle damage. If battles always start before 75% and food drops, it seems that the upgrade conditions will never be met. When the enemy upgrades to a higher-level base, higher-level units can crush them

That means this setting needs to have a fallback release, or unlock, to ensure that the upgrade can proceed smoothly, and food should not be set so high
In addition, the percentage and food can be adjusted according to the character of the file, not every AI is the same

**Comment by SMUnlimited** [comment]
It does have a fallback, it builds it in the order stated within the strategy, so ultimately each strategy needs updating if they are incorrect or particular strategies can set there own lower block limits based on whichever conditions are required. 

This block just prevents it building much much earlier than the strategy says unless its clear the AI is dominating in food, but the unlock doesn't mean they will definitely tier up either.

**Comment by SMUnlimited** [comment]
Done all I can in a general cases, anything else needs tweaks to the strategies themselves.
