### ISSUE TITLE
ghoul Harvest need fix

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#469]
some time , AI no wood and no ghoul , like `Count < 5` ， maybe all die
`attacking_ghouls` will is 0
but now  `TownCountDone(racial_ghoul) == harvesting_ghouls` -- highly probable event
so `TownCountDone(racial_ghoul) - attacking_ghouls - harvesting_ghouls` always 0 ， then `HarvestWood` always 0
and `call HarvestWood(0, Max(harvesting_ghouls,0))`  will be overwritten by subsequent instructions ？？？

and here should `call FormGroupAM`?? why

```
  if race_has_ghouls then
    call HarvestWood(0, Max(harvesting_ghouls,0))
    if peons_assigned and ghouls_in_attack then
      call HarvestWood(0, Max(TownCountDone(racial_ghoul) - attacking_ghouls - harvesting_ghouls,0)) // spare ghouls not doing anything and not assigned to attack yet
      call FormGroupAM(0) // in an attack so don't let harvest AI override attack
    else
      call HarvestWood(0, Max(TownCountDone(racial_ghoul) - harvesting_ghouls,0)) // spare ghouls not doing anything
    endif  
    set peons_assigned = true
```

---------------------------------------------------------------------------------------------------------------------
fix
```
  if race_has_ghouls then
    //call HarvestWood(0, Max(harvesting_ghouls,0))
    if take_all_ghouls_along then // no need harvest wood
    elseif TownCountDone(racial_ghoul) < 4 or GetWood() < 400 then
      call HarvestWood(0, Min(TownCountDone(racial_ghoul), 5))
    elseif peons_assigned and ghouls_in_attack then
      call HarvestWood(0, Max(TownCountDone(racial_ghoul) - attacking_ghouls - harvesting_ghouls,0)) // spare ghouls not doing anything and not assigned to attack yet
      //call FormGroupAM(0) // in an attack so don't let harvest AI override attack
    else
      call HarvestWood(0, Max(TownCountDone(racial_ghoul) - harvesting_ghouls,0)) // spare ghouls not doing anything
    endif
    set peons_assigned = true
```

**Comment by SMUnlimited** [comment]
Harvest calls are additive, so it doesn't override unless you call clearharvest between each call. 

FormGroup was being called as otherwise harvest code overrides attack code and was pulling ghouls back from the attack to harvest.

I would suspect harvesting_ghouls is 0 to result in no ghouls harvesting or the attack has been set to "take_all_ghouls_along"

**Comment by jzy-chitong56** [comment]
"take_all_ghouls_along"
Is there a situation where it has not been turned off and has been turned on continuously after starting to play?

**Comment by jzy-chitong56** [comment]
if wood > minimum_peon_wood then
    set take_all_ghouls_along = true
  elseif wood < minimum_peon_wood or gn < 2 then
    set take_all_ghouls_along = false
  endif

**Comment by SMUnlimited** [comment]
Just because ghoul count is low doesn't mean we should cut more wood.
