### ISSUE TITLE
Function BuildAdvUpgr2 is incomplete, which might invalidate the dynamic strategy system.

### ISSUE THREAD

**Issue by Pixyy** [SMUnlimited/AMAI#47]
The new dynamic strategy system uses the function BuildAdvUpgr2 to control upgrades. For example:
    if tier == 1 then
	endif
	call BuildAdvUpgr2(1, UPG_ULTRAVISION, 1, TownCountDone(ARCHER) + TownCountDone(HUNTRESS), 5, 3, 20)

There is no description of the function BuildAdvUpgr2 in the manuals reference section, so I checked common.eai and found these:

function BuildAdvUpgr takes integer qty, integer unitid, integer starttier, integer unitcount, integer maxunits, integer tierprio, integer prio returns nothing
	if tier >= starttier then
	if unitcount > 0 then
	    if qty >= tier-starttier+1 then
			call BuildUpgr(tier-starttier + 1, unitid, R2I(LinearInterpolation(0, maxunits, 1, prio + ((tier-starttier)* tierprio) , unitcount)))
		else
			// If tier greater than the start tier and qty is less than the difference between the two
			call BuildUpgr(qty, unitid, R2I(LinearInterpolation(0, maxunits, 1, prio + ((tier-starttier)* tierprio), unitcount)))
		endif
	endif
	endif
endfunction

// unitper - Number of units to give a 1% chance of building upgrade
function BuildAdvUpgr2 takes integer qty, integer upgid, integer starttier, integer unitcount, real unitper, integer max, integer prio returns nothing
//set num = (R2I((100 - FoodUsed())/GetFoodUsed(old_id[])) - 1) * prio_q_inc   // build upgrade priority at priority of unit
	if tier >= starttier then
	if unitcount > 0 then
		if GetRandomInt(1, 100) <= Min(R2I(unitcount/unitper), max) then
	    if qty >= tier-starttier+1 then
			call BuildUpgr(tier-starttier + 1, upgid, prio)
		else
			// If tier greater than the start tier and qty is less than the difference between the two
			call BuildUpgr(qty, upgid, prio)
		endif
		endif
	endif
	endif
endfunction

Both BuildAdvUpgr function call function BuildUpgr. The last parameter of function BuildUpgr is about priority. The function BuildAdvUpgr changes the priority by using the R2I code. But in function BuildAdvUpgr2 the priority hasn't been changed at all.

I guess the function BuildAdvUpgr2 is incomplete. This is a huge bug that could let the dynamic strategy system do more harm than good for AMAI. Need to fix soon.

**Comment by SMUnlimited** [comment]
Adding some clarification and adding a small bonus for the tiers but this method uses random chance with the priority immediately at max value if the random check passes. Its not designed to fully replace other uses as these are just a backup to ensure all strategies do eventually perform upgrades.

**Comment by SMUnlimited** [comment]
Otherwise working as intended. Raise something new if an in game issue with it.
