### ISSUE TITLE
My Version of NEW AMAI update

### ISSUE THREAD

**Issue by Pixyy** [SMUnlimited/AMAI#50]
AMAI 3.10c: https://github.com/Pixyy/AMAI

**Comment by SMUnlimited** [comment]
Thanks for the updates, you have clearly spent alot of time on this which will be worth merging in for all.

I'll move it to a new branch as commits are a bit messy so needs a bit of cleanup and review before full merge in.

**Comment by Pixyy** [comment]
I am glad to make my contribution to this project.
What can I do to help you to clear up? Do you need the English version of the AMAI 3.10c changelog so that we are on the same page? 
If you have any questions about the changes and codes, just ask.
Happy New Year to you and to AMAI. 2022 is the 15th year of AMAI (since 2007). Though Warcraft 3 is no longer popular, I believe we can still do something to make this game and AI better.
Long live the AMAI.

**Comment by SMUnlimited** [comment]
Working through it here: https://github.com/SMUnlimited/AMAI/tree/pixyycleanup

Got most of it in and documented now, just got all your strategy changes left to merge in. And some of my own testing of it.

**Comment by SMUnlimited** [comment]
Most of your changes are now merged to master ready for the 3.1 release, with a few tweaks here and there. 

Did a test 4v4 AMAI vs vanilla AI team battle, AMAI absolutely destroyed the vanilla AI which was very impressive.
