### ISSUE TITLE
Easy AI income

### ISSUE THREAD

**Issue by WhiteKapi** [SMUnlimited/AMAI#52]
![Screenshot (961)](https://user-images.githubusercontent.com/97306028/148583010-dd751ba2-27aa-4280-9291-c830a45df0de.png)

Shouldn't easy AI get less income?

**Comment by SMUnlimited** [comment]
AMAI doesn't touch the difficulty bonuses, but there is no reduced income on easy even in vanilla its hardcoded micro and attack settings that are tweaked by that setting. Only increased income for insane computers.

**Comment by WhiteKapi** [comment]
> AMAI doesn't touch the difficulty bonuses, but there is no reduced income on easy even in vanilla its hardcoded micro and attack settings that are tweaked by that setting. Only increased income for insane computers.

so easy computer really makes it weaker at micro and attack?

**Comment by SMUnlimited** [comment]
Yes its a very minimal effect, the handicap setting you can set at game creation has more of an effect.
