### ISSUE TITLE
The counter system is still called too frequently

### ISSUE THREAD

**Issue by Pixyy** [SMUnlimited/AMAI#53]
Test with 3.11.
I watched a match between two AMAI from an observer's point of view so that I could see all the text they send about counter-strategy. In the mid-game, the text became so frequently that there were 3 texts in 26s, and the strategy that AI used didn't change at all. The only thing that has changed is the enemy units that need to be countered.

![屏幕截图(1017)](https://user-images.githubusercontent.com/88197432/148963204-e8eb934d-cfe6-46ac-a1d0-32751996c150.png)
![屏幕截图(1019)](https://user-images.githubusercontent.com/88197432/148963392-fb911ab4-322c-4fc7-b13b-0a34b6ede2a7.png)

As you can see, there are 3 texts from 9:53 to 10:19.

I think the parameter counter_timer in races.eai has something with this issue.
In lines 718 and 749, This parameter is divided by 2.
`local integer counter_timer = R2I(I2R(-strat_minimum_time[strategy] * (4 - Min(3, tier)))/(3*sleep_multiplier*Max(difficulty - 1, 1))/2)`
Maybe we should remove this or replace it with multiply by 2?

**Comment by SMUnlimited** [comment]
The counter is designed to change more than the strategy does, but it shouldn't be changing 3 times over 26 seconds, that's definitely a bug in a calculation or logic somewhere.

**Comment by SMUnlimited** [comment]
Seems to be an issue with the insane difficulty setting at tier 3 its reducing the timer to the strat_minimum_time which for this strategy is only 20 which is one of the lowest ones. This is normally expected to be 20*6=120 seconds.

Then there supposed to be 2 counter changes allowed during the strategy but with the timer so low its only 10 seconds before next evaluation.

Additionally the counter change is tracked separate to the strategy but its possible for the strategy to just change and then the counter timer also need to change. I think both the logic and the timer will need a rework to fix both issues.

**Comment by SMUnlimited** [comment]
Added some improvements to the PR which will need testing out before I push to master
1) Fix the strategy timer as it was evaluating incorrectly.
2) Reduced the effect of tiers and insane difficulty on the timer
3) Fixed some strategies with a min amount of time which was way to long
4) Bound counters to re-evaluate once half way through the strategy and then again when strategies are re-evaluated (whether it changes or not)
