### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#58]
HI，I am a china player  ， but  I English is not good, sorry（ this written for baidu translate ） , and I code level is low low  low  

I want to update 2.6.1， for no Reforged player, because the new versions only 1.32+, start want fix the Chinese language 
So I refer to your modification, I fix Chinese language and redo the Chinese all file  ,include resources Tips （I want to  the file sync to 3.1.1）

temporary code to Blizzard.eai

`    string you_no_gold = ""
    string i_no_gold = ""
    string tribute_of_gold = ""
    string gold_received_thanks = ""
    string you_no_lumber = ""
    string i_no_lumber = ""
    string tribute_of_lumber = ""
    string lumber_received_thanks = ""`

`	    if language == "Chinese" then
	      call DisplayFromToPlayer(Comp, Commander, I2S(res_amount) + gold_received_thanks)
	    else
	      call DisplayFromToPlayer(Comp, Commander, "Gift of "+ I2S(res_amount) + " Gold has been received. Thanks.")
	    endif
    //You don't have enough Gold to share`

------------------------------------------------------------

Now I want synchronized some changes to 2.6.1 for 3.00 and 3.1.1 (maybe can call the new  Versions 2.6.2? ha... ) , but I have some questions

`Dynamic strategies are now enabled and act as a fallback for all strategies.
Hardcoded strategies still set the theme and initial build orders.
But AMAI will now have an element of countering what the enemies have built and what it has already built.
Dynamic strategies change more frequently than the chosen fixed strategy theme.
Dynamic strategies pick the attack type they are countering and a unit to focus on building until its next check.`

i can't add to 2.6.1 , I code level ....The new function beyond my cognition, so I just change Dynamo Strategy for Pixyy's code

**`Profiles can now be reused by AI players. This is useful for > 12 players in a game as there is not always enough profiles to set unique profiles.`**
you have 26 Profiles  > 24 , why you said ' not always enough profiles' ? and I can't restore modification ，I find in 2.54d , Profilesis can be reused ,  I can not find  the code cancel the reused , it not `_exitwhen (p_race[profile] == R_RANDOM or p_race[profile] == own_race) and (not IsProfileUsed(profile) or i > profile_length)_` , because the AI name reused -- can't see who's talking

maybe is more prophase change?

**Improved support for 24 players.**
the 3.1.1 have some improvement
Blizzard.eai and Blizzardx.j have some `11/12 player/coloer `  can change to `23/24` (Remember the` 11 sheep`  ）
If you don't modify it ， the 13~24 player Chat only use English 
 
Jobs
MICRO_HERO.eai and REVEAL_ENEMY.eai have the player ,  maybe need change to 24

TFT
GlobalSettings.txt
`slm_start	6	how many computer players is needed tor the sleep multiplier to start increasing.
slm_end	22	how many computer players is needed tor the sleep multiplier to stop increasing.`
the change maybe can let the game run more smoothly(24 player is not smoothly)

maybe have more file need change player , I don't remember

my Versions have 2,  1.24~1.32 only 12 player,  1.29~1.32 can 24 play

**the AI can not use 'DRUID_TALON_M(edtm)'**
Pixyy find the questions ,but he remove the TALON Strengths , I see the DRUID_CLAW and SPIRIT_WALKER for StandardUnits.txt , but  cann't find the solution for the questions . 

and I find another question:  StandardUnits.txt
SPIRIT_WALKER	ospm
SPIRIT_WALKER_M	ospw

Blizzard code is  `SPIRIT_WALKER ospw`	`SPIRIT_WALKER_M	ospm`  , I think is the bug, so I change  the code , but orc can not build SPIRIT_WALKER， I want know why. 
and I change code to `DRUID_TALON_M  edot` and `DRUID_TALON edtm` ,hope AI can use the DRUID_TALON_M , result is  elf can not build DRUID_TALON

`    call BuildUnit(10, DRUID_TALON_M , 45)`  and `call SetBuildReact(32, 6, DRUID_TALON_M , 0, DRUID_TALON_M , enemy_air, 4, 10, 88) ` is invalid

thank

**Comment by SMUnlimited** [comment]
Fixed by https://github.com/SMUnlimited/AMAI/pull/65

Waiting for fixes to master before closing.

**Comment by SMUnlimited** [comment]
Various fixed now ported.
