### ISSUE TITLE
do not upgrade hall

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#62]
if    plot -  Game Options  - game data version  is no  The latest version

then only Undead will  upgrade hall

because upgrade  BuildSequence.ai have the code
`global_build_sequence`
`call DefendTownsDone(1, NECROPOLIS_1, 95) `
`call DefendTownsCond(1, NECROPOLIS_2, 7600, 20000, 0, 90)`

but
`call BuildUnit(1, NECROPOLIS_3, 50)`
`call BuildUnit(1, hall, 50)`
can not work

**Comment by SMUnlimited** [comment]
Latest version can not support maps with game data set to old version due to incompatible changes in the tech tree.

You have to find and use a really really old AMAI version.
