### ISSUE TITLE
war3 1.31, AMAI 2.6.1 hero not learning skills

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#63]
**esting environment**
war3 1.31
amai 2.6.1

**bug**
hero can not learning skills
all hero not learning 
human  ud ore elf all not learning 

if you watch Replay，switch AI player， you can see the hero head portrait have skill numbers

but change game Version ，they will learning ,only 1.31 can not

**Comment by SMUnlimited** [comment]
Sorry your translator didn't do a good job here, not sure what the issue is.

**Comment by jzy-chitong56** [comment]
translator modified

**Comment by SMUnlimited** [comment]
Hmm, not sure why this would happen unless its a bug in that version of war3. Skill id's haven't changed.
