### ISSUE TITLE
Impossible to defeat Insane AI

### ISSUE THREAD

**Issue by Ali229** [SMUnlimited/AMAI#70]
I can defeat 2 non-amai insane computers but with AMAI it's just absurd 25 population vs about 70+ in the same time, I see people on youtube defeating insane AMAI with mass towers and don't believe there is any other way to accomplish this, which is a boring way to play imo. Is there anyway I can reduce the amount of cheat insane AMAI uses?

**Comment by SMUnlimited** [comment]
AMAI is much harder than the original AI but they are not unbeatable and there are gameplay actions that can outright break them.

Insane AI's have double resources which is what makes them dangerous.
Ultimately its intended that
Insane = Map Hacker
Normal = Fair

There is no other scaling back of ability between the two though so just try back on normal.

**Comment by Ali229** [comment]
Unfortunately normal is just too easy for me... I was thinking maybe I could reduce the amount of gold insane gets...

**Comment by jzy-chitong56** [comment]
> Unfortunately normal is just too easy for me... I was thinking maybe I could reduce the amount of gold insane gets...

you need increase noemal gold,then easy = fair
