### ISSUE TITLE
 Blizzard.eai PLAYER_NEUTRAL_AGGRESSIVE Omission

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#72]
https://github.com/SMUnlimited/AMAI/blob/bcb245a355677c4b821151765a50af826125ba00/Blizzard.eai#L767

 14 >> PLAYER_NEUTRAL_AGGRESSIVE 

but i do not know why , why donot used  bj_PLAYER_NEUTRAL_EXTRA (player 26) 

because it was 14 , then for 24player , should  is  26

test tell me , if used AGG ,the [all play] can not choice ，because  the 27 player will tips we no allies

**Comment by SMUnlimited** [comment]
Fixed in https://github.com/SMUnlimited/AMAI/commit/1fa304f9eb61422ea4fc6d158e15803d59cfcf25
