### ISSUE TITLE
Ability to share control with the AMAI

### ISSUE THREAD

**Issue by SMUnlimited** [SMUnlimited/AMAI#79]
From [gartoll](https://www.hiveworkshop.com/members/gartoll.300592/)
1) Add an option to share units with the AMAI. Like, a button that gives you control over the AMAI without it losing theirs, similarly to online Tema games, where you can share unit control with your allies. It could also go vice versa, meaning both you and the AMAI ally/allies you give control can access your units.

2) When a bot leaves, instead of destroying their building and units, they give full control to their allies, humans or not, the same way you gain control over a leaver on online games. Extra points if there is a chance to give gold automatically to their allies before they leave.

**Comment by jzy-chitong56** [comment]
then have a other set   -- Attack group
now , the AI only control his Race Attack group Unit ， This means Domination/Occupation（like Undead Banshee and Dark Ranger） other Race Unit ,they only pull the unit go home 
and you must processing build , let ai build  other Race Factory and Unit

i think have a public group on comm....ai ,  AI can build other Race Unit and add other Race Unit to Attack group 

and this can solutions continue production ，have some map food upper limit > 100 or all Attack  Unit usedfood = 0 (they call this is Infinite food)

**Comment by jzy-chitong56** [comment]
![WC3ScrnShot_091722_200153_000](https://user-images.githubusercontent.com/48715223/190874401-a8c5bca8-1628-4df8-95ac-1984093c1d16.png)
the Dark Ranger control  orc Tauren ， but  Dark Ranger is elf
so AI can not used Tauren , and block up
@SMUnlimited

**Comment by SMUnlimited** [comment]
Part 1 Implemented

**Comment by jzy-chitong56** [comment]
i use this let ai take unknow unit 

But I'm worried that there are too many search codes for this type of unit group
Because 23 computer let games FPS drops , Single digit
```
function AttackGroupAddUnknown takes nothing returns nothing
  local group g = CreateGroup()
  local unit u = null
  local integer id = 0
  local integer i = 0
  call GroupEnumUnitsOfPlayer(g, ai_player, null)
  set g = SelectByAlive(g,true)
  set g = SelectUnittype(g, UNIT_TYPE_PEON, false)
  set g = SelectUnittype(g, UNIT_TYPE_STRUCTURE, false)
  loop
    exitwhen i >= attack_length
    set g = SelectById(g, old_id[attack_units[i]], false)
    set i = i + 1
  endloop
  loop
    set u = FirstOfGroup(g)
    exitwhen u == null
    set id = GetUnitTypeId(u)
    if not IsUnitType(u,UNIT_TYPE_SUMMONED) and id != 'ngir' and not IsUnitInGroup(u, unit_healing) and not IsUnitHidden(u) and (IsUnitType(u, UNIT_TYPE_ATTACKS_FLYING) or IsUnitType(u, UNIT_TYPE_ATTACKS_GROUND)) then
      call AddAssault(60,id)  //other hero and unit , like other race and custom
    endif
    call GroupRemoveUnit(g, u)
  endloop
  call DestroyGroup(g)
  set g = null
endfunction
```

**Comment by SMUnlimited** [comment]
Added human ally support so they don't give up. But its more difficult to get AMAI to control other AMAI units as per above. 

Only way would be to change the player controlling the units directly to the other AMAI if there are no human players and its the same "race". Different races at the same time are probably not going to happen.

**Comment by jzy-chitong56** [comment]
I believe we have forgotten one factor - the personality of AI

I suggest

There is still a surrender main switch , This can control whether AI runs failure detection JOB , Default On
- In shared mode, it is Off by default ,  AI Will not surrender
- In control mode, players can use the console to switch switches


---------------------------------------------------------------------------------
When the switch is turned Off ,  AI runs failure detection JOB

when AI discovering oneself about to fail ，they will surrender

Based they personality
- Some AI still self destruct all units
- Some AI will enable shared control for allies  -- if have allies  
- Some AI will desperate attack
- Some AI randomly select one from above

**Comment by SMUnlimited** [comment]
https://github.com/SMUnlimited/AMAI/commit/81845bef75ecb7b9e7d8e1e90dcf4fbecd327cf4 

In team games desperation attacks are not that useful either so have disabled that as well as the suicide unless they are the last player in the team.

The stubborn ai's still will fight to complete death, but others will end up shared or absorbed if possible.
