### ISSUE TITLE
Reinstalling AMAI on maps multiple times results in map file size increasing

### ISSUE THREAD

**Issue by SMUnlimited** [SMUnlimited/AMAI#80]
After many reinstalls of AMAI on the same map, the map will be much bigger than it should be (seems to grow infinitely)

Might be related to the MPQ not being compacted after changes.

Workaround: install onto the original fresh map.

**Comment by jzy-chitong56** [comment]
Is it possible to prepare a temporary directory  ， here have MPQ all file
b.j  c.j xx.ai
but the file is 0kb, no code
we installs  AMAI , Write first the 0kb file ,and then we Write real file
