### ISSUE TITLE
Night Elf Strategy - Ancient of War Rush

### ISSUE THREAD

**Issue by paulo101977** [SMUnlimited/AMAI#85]
Ability to send the Ancient Of War along with an archer to attack the first field of creeps. Then the hero also helps, to gain XP.
As in the image below:

EDITED: This is a common strategy when playing night elf.

![image](https://user-images.githubusercontent.com/5838041/190877895-6c51b047-6899-4c5e-8f4f-5263156a88ff.png)

**Comment by SMUnlimited** [comment]
Current issues with ancient of war rush logic: https://github.com/SMUnlimited/AMAI/commit/84dc1ff52589763ccb7091db7423378bf482c2cb

- never uproots if its training units.
- Team alliance targeting overrides the rush logic.
