### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by WhiteKapi** [SMUnlimited/AMAI#88]
I tried installing it with powershell but the name in game it's still "computer". Before I could just open MPQEditor, open a map, and add the scripts folder from TFT but it's not working anymore. This is before installing it and after in MPQeditor:
![Screenshot (292)](https://user-images.githubusercontent.com/97306028/193450344-a7df421a-cdcc-4f05-a3ac-63ed7470c698.png)
![Screenshot (291)](https://user-images.githubusercontent.com/97306028/193450346-c75f85c0-2143-4bc2-8255-4697bc1f550b.png)
This is the powershell: 
![Screenshot (290)](https://user-images.githubusercontent.com/97306028/193450352-428efbbb-53ae-48de-a1c6-5374ddda4642.png)
This only happens with AMAI 3.2.1

**Comment by SMUnlimited** [comment]
Version in Master already fixed to use MPQEditor which fixes the map list becoming messed up. But that has always been the case previously with the AMAI installs.

The MPQEditor approach you used manually should still be working fine regardless.

**Comment by paulo101977** [comment]
> Version in Master already fixed to use MPQEditor which fixes the map list becoming messed up. But that has always been the case previously with the AMAI installs.
> 
> The MPQEditor approach you used manually should still be working fine regardless.

It seems to be a problem with relative path.
