### ISSUE TITLE
How to use AMAI for custom maps?

### ISSUE THREAD

**Issue by velicue** [SMUnlimited/AMAI#9]
Hi all I made a custom map which works like melee but have new custom units. I looked it up online and it says it's possible to modify AMAI to let it work on custom maps. However the old "developer manual" seems to be no longer accessible and I couldn't find anything that tells me how to do that. Is it possible to get a tutorial about this on github? Many thanks.

**Comment by SMUnlimited** [comment]
The manual is still available in the gitrepo, eventually i'll convert it to the Wiki: https://github.com/SMUnlimited/AMAI/tree/master/Manual

It can be a bit of work depending on how many custom units you are dealing with.

**Comment by velicue** [comment]
Got it, thanks! BTW originally we need to use the "developer version" of the tool to do this. Is this repo containing the "developer version" of the AMAI?

**Comment by SMUnlimited** [comment]
Yes, but i have merged all the different versions into 1 to make it easier to distribute going forwards.

**Comment by velicue** [comment]
Got it, agree that this is much clearer, thanks!
