### ISSUE TITLE
MICRO_HERO have a num

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#91]
the **9** should is NEUTRAL_COUNT ?

constant integer NEUTRAL_COUNT = 10

https://github.com/SMUnlimited/AMAI/blob/387b1507073017dd297023fe17d478a85ebf447f/Jobs/MICRO_HERO.eai#L166

**Comment by SMUnlimited** [comment]
Actions are not related to the neutral count.
